// Sanskrit word glossary for word-by-word translation tooltips.
// Keys are lowercase IAST forms. Hyphened compound parts are separate entries.
// Each entry: { meaning, root?, grammar?, related? }

export interface GlossaryEntry {
  meaning: string
  root?: string       // dhātu / verbal root
  grammar?: string    // grammatical form (nom. sg., etc.)
  related?: string    // related/compound context
}

// Common vocabulary across Bhagavad-gītā, Śrīmad-Bhāgavatam, Brahma-saṁhitā, etc.
export const glossary: Record<string, GlossaryEntry> = {
  // ── Pronouns & particles ──
  'aham': { meaning: 'I', grammar: 'nom. sg.' },
  'ahaṁ': { meaning: 'I', grammar: 'nom. sg.' },
  'mām': { meaning: 'Me (to Me)', grammar: 'acc. sg.' },
  'māṁ': { meaning: 'Me (to Me)', grammar: 'acc. sg.' },
  'mayi': { meaning: 'in Me / upon Me', grammar: 'loc. sg.' },
  'me': { meaning: 'My / to Me', grammar: 'gen./dat. sg.' },
  'mat': { meaning: 'My / from Me', grammar: 'prefix' },
  'mad': { meaning: 'My / of Me', grammar: 'prefix' },
  'mama': { meaning: 'My', grammar: 'gen. sg.' },
  'tvām': { meaning: 'you (to you)', grammar: 'acc. sg.' },
  'tvāṁ': { meaning: 'you (to you)', grammar: 'acc. sg.' },
  'tava': { meaning: 'your', grammar: 'gen. sg.' },
  'te': { meaning: 'your / to you', grammar: 'gen./dat. sg.' },
  'sa': { meaning: 'he / that', grammar: 'nom. sg. masc.' },
  'sā': { meaning: 'she / that', grammar: 'nom. sg. fem.' },
  'tat': { meaning: 'that', grammar: 'nom./acc. sg. neut.' },
  'tad': { meaning: 'that', grammar: 'nom./acc. sg. neut.' },
  'tam': { meaning: 'him / that', grammar: 'acc. sg. masc.' },
  'tām': { meaning: 'her / that', grammar: 'acc. sg. fem.' },
  'tasya': { meaning: 'his / of that', grammar: 'gen. sg.' },
  'ye': { meaning: 'who / those who', grammar: 'nom. pl. masc.' },
  'yathā': { meaning: 'as / just as', grammar: 'indecl.' },
  'tathā': { meaning: 'so / in that way', grammar: 'indecl.' },
  'yat': { meaning: 'which / that which', grammar: 'nom./acc. neut.' },
  'yad': { meaning: 'which / that which', grammar: 'nom./acc. neut.' },
  'yaḥ': { meaning: 'who', grammar: 'nom. sg. masc.' },
  'yo': { meaning: 'who', grammar: 'nom. sg. masc.' },
  'idam': { meaning: 'this', grammar: 'nom./acc. neut.' },
  'idaṁ': { meaning: 'this', grammar: 'nom./acc. neut.' },
  'iti': { meaning: 'thus / so', grammar: 'indecl.' },
  'eva': { meaning: 'indeed / certainly / only', grammar: 'indecl.' },
  'ca': { meaning: 'and', grammar: 'indecl.' },
  'vā': { meaning: 'or', grammar: 'indecl.' },
  'na': { meaning: 'not', grammar: 'indecl.' },
  'hi': { meaning: 'for / indeed / because', grammar: 'indecl.' },
  'tu': { meaning: 'but / however', grammar: 'indecl.' },
  'api': { meaning: 'also / even', grammar: 'indecl.' },
  'iva': { meaning: 'like / as if', grammar: 'indecl.' },
  'ataḥ': { meaning: 'therefore', grammar: 'indecl.' },
  'ata': { meaning: 'therefore', grammar: 'indecl.' },
  'tataḥ': { meaning: 'then / from that', grammar: 'indecl.' },
  'atra': { meaning: 'here / in this', grammar: 'indecl.' },
  'evaṁ': { meaning: 'thus / in this way', grammar: 'indecl.' },
  'evam': { meaning: 'thus / in this way', grammar: 'indecl.' },
  'mā': { meaning: 'do not', grammar: 'prohibitive particle' },
  'tāṁs': { meaning: 'them', grammar: 'acc. pl. masc.' },
  'tathaiva': { meaning: 'in the same way', grammar: 'indecl.' },

  // ── Key nouns ──
  'sarva': { meaning: 'all / everything', grammar: 'adj./pron.' },
  'sarvaṁ': { meaning: 'everything', grammar: 'acc./nom. sg. neut.' },
  'sarvasya': { meaning: 'of all / of everything', grammar: 'gen. sg.' },
  'sarvam': { meaning: 'everything', grammar: 'acc./nom. sg. neut.' },
  'sarvāṇi': { meaning: 'all (things)', grammar: 'nom./acc. pl. neut.' },
  'sarve': { meaning: 'all', grammar: 'nom. pl. masc.' },
  'ātmā': { meaning: 'the self / the soul', grammar: 'nom. sg.' },
  'ātmānaṁ': { meaning: 'the self (oneself)', grammar: 'acc. sg.' },
  'ātmānam': { meaning: 'the self (oneself)', grammar: 'acc. sg.' },
  'ātmanaḥ': { meaning: 'of the self', grammar: 'gen. sg.' },
  'ātman': { meaning: 'self / soul', grammar: 'stem' },
  'dharma': { meaning: 'duty / righteousness / nature', root: '√dhṛ (to hold)' },
  'dharmān': { meaning: 'duties / dharmas', grammar: 'acc. pl.' },
  'kṛṣṇa': { meaning: 'Kṛṣṇa — the all-attractive Supreme Lord', grammar: 'proper noun' },
  'kṛṣṇaḥ': { meaning: 'Kṛṣṇa', grammar: 'nom. sg.' },
  'govinda': { meaning: 'Govinda — giver of pleasure to cows & senses', grammar: 'proper noun' },
  'govindam': { meaning: 'to Govinda', grammar: 'acc. sg.' },
  'govindaḥ': { meaning: 'Govinda', grammar: 'nom. sg.' },
  'bhagavān': { meaning: 'the Supreme Lord (possessor of all opulences)', grammar: 'nom. sg.' },
  'bhagavat': { meaning: 'the Supreme Lord', grammar: 'stem' },
  'bhagavate': { meaning: 'unto the Supreme Lord', grammar: 'dat. sg.', related: 'oṁ namo bhagavate vāsudevāya — "I offer obeisances to Lord Vāsudeva"' },
  'bhagavataḥ': { meaning: 'of the Supreme Lord', grammar: 'gen. sg.' },
  'bhagavatā': { meaning: 'by the Supreme Lord', grammar: 'inst. sg.' },
  'bhagavantam': { meaning: 'the Supreme Lord', grammar: 'acc. sg.' },
  'brahman': { meaning: 'the Absolute / Brahman / spirit', grammar: 'stem' },
  'brahma': { meaning: 'Brahman / the Absolute', grammar: 'nom. sg. neut.' },
  'yoga': { meaning: 'link / union / practice of connecting with God', root: '√yuj (to yoke)' },
  'yogī': { meaning: 'practitioner of yoga', grammar: 'nom. sg.' },
  'karma': { meaning: 'action / work / reaction', root: '√kṛ (to do)' },
  'karmaṇā': { meaning: 'by action', grammar: 'inst. sg.' },
  'jñāna': { meaning: 'knowledge / wisdom', root: '√jñā (to know)' },
  'jñānam': { meaning: 'knowledge', grammar: 'acc./nom. sg.' },
  'jñānavān': { meaning: 'one who has knowledge', grammar: 'nom. sg.' },
  'bhakti': { meaning: 'devotion / devotional service', root: '√bhaj (to serve/worship)' },
  'bhaktyā': { meaning: 'with devotion', grammar: 'inst. sg.' },
  'bhakta': { meaning: 'devotee', root: '√bhaj' },
  'bhaktaḥ': { meaning: 'a devotee', grammar: 'nom. sg.' },
  'bhakto': { meaning: 'a devotee', grammar: 'nom. sg. (sandhi)' },
  'guru': { meaning: 'spiritual master / heavy / weighty', grammar: 'nom. sg.' },
  'guruḥ': { meaning: 'the spiritual master', grammar: 'nom. sg.' },
  'guror': { meaning: 'of the guru', grammar: 'gen. sg.' },
  'deva': { meaning: 'divine being / god', root: '√div (to shine)' },
  'devaḥ': { meaning: 'the Lord / god', grammar: 'nom. sg.' },
  'devam': { meaning: 'the Lord', grammar: 'acc. sg.' },
  'jagat': { meaning: 'the world / universe', grammar: 'nom./acc. sg.' },
  'loka': { meaning: 'world / planet', grammar: 'stem' },
  'lokān': { meaning: 'worlds', grammar: 'acc. pl.' },
  'māyā': { meaning: 'illusion / material energy', root: '√mā (to measure)' },
  'māyāṁ': { meaning: 'illusory energy', grammar: 'acc. sg.' },
  'prakṛti': { meaning: 'material nature', grammar: 'nom. sg.' },
  'prakṛtiṁ': { meaning: 'material nature', grammar: 'acc. sg.' },
  'puruṣa': { meaning: 'person / the supreme enjoyer', grammar: 'stem' },
  'puruṣaṁ': { meaning: 'the supreme person', grammar: 'acc. sg.' },
  'puruṣam': { meaning: 'the supreme person', grammar: 'acc. sg.' },
  'rūpa': { meaning: 'form / beauty', grammar: 'stem' },
  'rūpam': { meaning: 'form', grammar: 'acc./nom. sg.' },
  'rūpaṁ': { meaning: 'form', grammar: 'acc./nom. sg.' },
  'śakti': { meaning: 'energy / power', grammar: 'nom. sg.' },
  'līlā': { meaning: 'divine pastime / play', grammar: 'nom. sg.' },
  'prema': { meaning: 'pure love (for God)', grammar: 'nom. sg.' },
  'dhāma': { meaning: 'abode / dwelling place', grammar: 'nom. sg.' },
  'nāma': { meaning: 'name / the holy name', grammar: 'nom. sg.' },
  'mantra': { meaning: 'sacred syllable / prayer', root: '√man (to think)' },
  'pāda': { meaning: 'foot / lotus feet / verse quarter', grammar: 'stem' },
  'pādau': { meaning: 'two feet', grammar: 'nom./acc. dual' },
  'padaṁ': { meaning: 'position / abode / word', grammar: 'acc. sg.' },
  'padam': { meaning: 'position / abode / word', grammar: 'acc. sg.' },
  'veda': { meaning: 'knowledge / the Vedas', root: '√vid (to know)' },
  'vedaiḥ': { meaning: 'by the Vedas', grammar: 'inst. pl.' },
  'śāstra': { meaning: 'scripture', root: '√śās (to instruct)' },
  'saṁsāra': { meaning: 'cycle of birth & death', grammar: 'stem' },
  'mokṣa': { meaning: 'liberation / release', root: '√muc (to free)' },
  'mukti': { meaning: 'liberation', root: '√muc' },
  'karuṇā': { meaning: 'mercy / compassion', grammar: 'nom. sg.' },
  'karuṇayā': { meaning: 'out of mercy', grammar: 'inst. sg.' },
  'kṛpā': { meaning: 'mercy / grace', grammar: 'nom. sg.' },
  'kṛpāṁ': { meaning: 'mercy', grammar: 'acc. sg.' },
  'sat': { meaning: 'truth / eternal / the pious', grammar: 'stem' },
  'satāṁ': { meaning: 'of the saintly', grammar: 'gen. pl.' },
  'sādhu': { meaning: 'saintly person / excellent', grammar: 'nom. sg.' },
  'sādhūnāṁ': { meaning: 'of the saintly', grammar: 'gen. pl.' },
  'pāpa': { meaning: 'sin', grammar: 'stem' },
  'pāpebhyo': { meaning: 'from sins', grammar: 'abl. pl.' },
  'puṇya': { meaning: 'pious / meritorious', grammar: 'adj.' },

  // ── Key verbs ──
  'bhajāmi': { meaning: 'I worship / I serve', root: '√bhaj', grammar: '1st sg. pres.' },
  'bhajante': { meaning: 'they worship', root: '√bhaj', grammar: '3rd pl. pres.' },
  'bhajāmy': { meaning: 'I worship', root: '√bhaj', grammar: '1st sg. pres. (sandhi)' },
  'bhajāmī': { meaning: 'I worship', root: '√bhaj', grammar: '1st sg. pres.' },
  'bhava': { meaning: 'become! / being / existence', root: '√bhū (to be)', grammar: 'imperative' },
  'bhavati': { meaning: 'becomes / is', root: '√bhū', grammar: '3rd sg. pres.' },
  'prapadyate': { meaning: 'surrenders', root: 'pra + √pad', grammar: '3rd sg. pres.' },
  'prapadyante': { meaning: 'they surrender', root: 'pra + √pad', grammar: '3rd pl. pres.' },
  'pravartate': { meaning: 'proceeds / emanates', root: 'pra + √vṛt', grammar: '3rd sg. pres.' },
  'jānāti': { meaning: 'knows', root: '√jñā', grammar: '3rd sg. pres.' },
  'paśyati': { meaning: 'sees', root: '√paś/dṛś', grammar: '3rd sg. pres.' },
  'namaskuru': { meaning: 'offer obeisances!', root: 'namas + √kṛ', grammar: 'imperative' },
  'namaḥ': { meaning: 'obeisances / I bow', grammar: 'indecl.' },
  'namo': { meaning: 'obeisances — from namaḥ, changed by sandhi (aḥ → o before voiced consonants). See Rules → Sandhi for more.', grammar: 'indecl.' },
  'namāmi': { meaning: 'I bow / I offer obeisances', root: '√nam', grammar: '1st sg. pres.' },
  'jayati': { meaning: 'is victorious / conquers', root: '√ji', grammar: '3rd sg. pres.' },
  'jaya': { meaning: 'victory! / all glories', root: '√ji', grammar: 'imperative / exclamation' },
  'āśritāḥ': { meaning: 'having taken shelter', root: 'ā + √śri', grammar: 'nom. pl. past part.' },
  'mokṣayiṣyāmi': { meaning: 'I shall liberate', root: '√muc', grammar: '1st sg. future' },
  'prayacchati': { meaning: 'offers / gives', root: 'pra + √yam', grammar: '3rd sg. pres.' },
  'aśnāmi': { meaning: 'I eat / I accept', root: '√aś', grammar: '1st sg. pres.' },
  'sambhavāmi': { meaning: 'I appear / I manifest', root: 'sam + √bhū', grammar: '1st sg. pres.' },
  'nivasiṣyasi': { meaning: 'you will dwell / live', root: 'ni + √vas', grammar: '2nd sg. future' },
  'parityajya': { meaning: 'having abandoned', root: 'pari + √tyaj', grammar: 'gerund' },
  'ādhatsva': { meaning: 'fix! / place!', root: 'ā + √dhā', grammar: 'imperative' },
  'niveśaya': { meaning: 'engage! / absorb!', root: 'ni + √viś', grammar: 'causative imperative' },
  'vraja': { meaning: 'go! / take shelter!', root: '√vraj', grammar: 'imperative' },
  'śucaḥ': { meaning: 'grieve / lament', root: '√śuc', grammar: '2nd sg. subjunctive' },
  'matvā': { meaning: 'having understood', root: '√man (to think)', grammar: 'gerund' },
  'avatīrṇaḥ': { meaning: 'descended / incarnated', root: 'ava + √tṝ', grammar: 'past part.' },

  // ── Adjectives & descriptors ──
  'mahā': { meaning: 'great', grammar: 'prefix' },
  'mahātmā': { meaning: 'great soul', grammar: 'nom. sg.' },
  'para': { meaning: 'supreme / transcendental / other', grammar: 'adj.' },
  'paraṁ': { meaning: 'supreme', grammar: 'acc./nom. sg. neut.' },
  'param': { meaning: 'supreme', grammar: 'acc./nom. sg. neut.' },
  'parataraṁ': { meaning: 'superior', grammar: 'comparative' },
  'nitya': { meaning: 'eternal / always', grammar: 'adj.' },
  'nityaṁ': { meaning: 'eternally', grammar: 'adv.' },
  'sanātana': { meaning: 'eternal / everlasting', grammar: 'adj.' },
  'śāśvata': { meaning: 'eternal / permanent', grammar: 'adj.' },
  'avyaya': { meaning: 'imperishable / inexhaustible', grammar: 'adj.' },
  'acyuta': { meaning: 'infallible (name of Kṛṣṇa)', grammar: 'adj./noun' },
  'ananta': { meaning: 'unlimited / infinite', grammar: 'adj.' },
  'sundara': { meaning: 'beautiful', grammar: 'adj.' },
  'priya': { meaning: 'dear / beloved', grammar: 'adj.' },
  'śrī': { meaning: 'beauty / fortune / divine prefix of respect', grammar: 'prefix/noun' },
  'durlabhaḥ': { meaning: 'rare / hard to obtain', grammar: 'nom. sg.' },
  'su': { meaning: 'very / good / easily', grammar: 'prefix' },

  // ── Nouns — body/nature ──
  'manaḥ': { meaning: 'mind', grammar: 'nom./acc. sg.' },
  'mana': { meaning: 'mind', grammar: 'stem' },
  'manas': { meaning: 'mind', grammar: 'stem' },
  'buddhiṁ': { meaning: 'intelligence', grammar: 'acc. sg.' },
  'buddhi': { meaning: 'intelligence', root: '√budh (to know)' },
  'hṛdaya': { meaning: 'heart', grammar: 'stem' },
  'hṛdi': { meaning: 'in the heart', grammar: 'loc. sg.' },
  'deha': { meaning: 'body', grammar: 'stem' },
  'netra': { meaning: 'eye', grammar: 'stem' },
  'vāṇī': { meaning: 'speech / words', grammar: 'nom. sg.' },

  // ── Common BG words ──
  'prabhavo': { meaning: 'the origin / source', root: 'pra + √bhū', grammar: 'nom. sg.' },
  'prabhavaḥ': { meaning: 'the origin', grammar: 'nom. sg.' },
  'mattaḥ': { meaning: 'from Me', grammar: 'abl. sg.' },
  'budhā': { meaning: 'the wise', grammar: 'nom. pl.' },
  'bhāva': { meaning: 'nature / feeling / devotional ecstasy', grammar: 'stem' },
  'samanvitāḥ': { meaning: 'endowed with / possessed of', grammar: 'nom. pl.' },
  'patraṁ': { meaning: 'a leaf', grammar: 'acc. sg.' },
  'patram': { meaning: 'a leaf', grammar: 'acc. sg.' },
  'puṣpaṁ': { meaning: 'a flower', grammar: 'acc. sg.' },
  'puṣpam': { meaning: 'a flower', grammar: 'acc. sg.' },
  'phalaṁ': { meaning: 'a fruit', grammar: 'acc. sg.' },
  'phalam': { meaning: 'a fruit', grammar: 'acc. sg.' },
  'toyaṁ': { meaning: 'water', grammar: 'acc. sg.' },
  'toyam': { meaning: 'water', grammar: 'acc. sg.' },
  'prayatātmanaḥ': { meaning: 'of one with pure consciousness', grammar: 'gen. sg.' },
  'paritrāṇāya': { meaning: 'for the deliverance / protection', grammar: 'dat. sg.', root: 'pari + √trā' },
  'vināśāya': { meaning: 'for the destruction', grammar: 'dat. sg.', root: 'vi + √naś' },
  'duṣkṛtām': { meaning: 'of the miscreants', grammar: 'gen. pl.' },
  'saṁsthāpanārthāya': { meaning: 'for the establishment of', grammar: 'dat. sg.' },
  'yuge': { meaning: 'in an age / millennium', grammar: 'loc. sg.' },
  'śaraṇaṁ': { meaning: 'shelter / refuge', grammar: 'acc. sg.' },
  'śaraṇam': { meaning: 'shelter / refuge', grammar: 'acc. sg.' },
  'ekaṁ': { meaning: 'alone / one / only', grammar: 'acc. sg.' },
  'ekam': { meaning: 'alone / one / only', grammar: 'acc. sg.' },
  'ūrdhvaṁ': { meaning: 'upward / henceforth / beyond', grammar: 'adv.' },
  'saṁśayaḥ': { meaning: 'doubt', grammar: 'nom. sg.' },
  'nānyat': { meaning: 'no other', grammar: 'nom. sg. neut.' },
  'kiñcid': { meaning: 'anything', grammar: 'nom./acc. sg. neut.' },
  'kiñcit': { meaning: 'anything', grammar: 'nom./acc. sg. neut.' },
  'asti': { meaning: 'there is', root: '√as (to be)', grammar: '3rd sg. pres.' },
  'dhanañjaya': { meaning: 'O Dhanañjaya (Arjuna — winner of wealth)', grammar: 'voc.' },
  'protaṁ': { meaning: 'strung / pervaded', grammar: 'past part.' },
  'sūtre': { meaning: 'on a thread', grammar: 'loc. sg.' },
  'maṇi': { meaning: 'jewel / pearl', grammar: 'stem' },
  'gaṇā': { meaning: 'multitudes / groups', grammar: 'nom. pl.' },
  'gaṇāḥ': { meaning: 'groups', grammar: 'nom. pl.' },
  'bahūnāṁ': { meaning: 'of many', grammar: 'gen. pl.' },
  'bahūnām': { meaning: 'of many', grammar: 'gen. pl.' },
  'janmanām': { meaning: 'of births', grammar: 'gen. pl.' },
  'ante': { meaning: 'at the end', grammar: 'loc. sg.' },
  'vāsudevaḥ': { meaning: 'Vāsudeva (son of Vasudeva = Kṛṣṇa)', grammar: 'nom. sg.' },
  'vartmānuvartante': { meaning: 'follow the path', grammar: '3rd pl. pres.' },
  'vartma': { meaning: 'path', grammar: 'acc. sg.' },
  'manuṣyāḥ': { meaning: 'human beings', grammar: 'nom. pl.' },
  'pārtha': { meaning: 'O son of Pṛthā (Arjuna)', grammar: 'voc.' },
  'sarvaśaḥ': { meaning: 'in all respects', grammar: 'adv.' },
  'arjuna': { meaning: 'Arjuna (white/pure)', grammar: 'proper noun / voc.' },
  'kalau': { meaning: 'in the age of Kali', grammar: 'loc. sg.' },

  // ── Brahma-saṁhitā ──
  'veṇuṁ': { meaning: 'flute', grammar: 'acc. sg.' },
  'veṇum': { meaning: 'flute', grammar: 'acc. sg.' },
  'kvaṇantam': { meaning: 'playing / sounding', root: '√kvaṇ', grammar: 'pres. part. acc.' },
  'aravinda': { meaning: 'lotus', grammar: 'stem' },
  'dalāyatākṣam': { meaning: 'eyes like lotus petals', grammar: 'acc. sg.' },
  'barhāvataṁsam': { meaning: 'wearing a peacock feather ornament', grammar: 'acc. sg.' },
  'asitāmbuda': { meaning: 'dark cloud', grammar: 'compound' },
  'sundarāṅgam': { meaning: 'beautiful-limbed', grammar: 'acc. sg.' },
  'kandarpa': { meaning: 'Cupid / god of love', grammar: 'stem' },
  'koṭi': { meaning: 'ten million / countless', grammar: 'stem' },
  'kamanīya': { meaning: 'attractive / charming', grammar: 'adj.' },
  'viśeṣa': { meaning: 'special / extraordinary', grammar: 'stem' },
  'śobhaṁ': { meaning: 'beauty / splendor', grammar: 'acc. sg.' },
  'ādi': { meaning: 'original / primeval', grammar: 'adj./stem' },
  'cintāmaṇi': { meaning: 'wish-fulfilling gem', grammar: 'stem' },
  'prakara': { meaning: 'multitude / wall', grammar: 'stem' },
  'sadmasu': { meaning: 'in the abodes', grammar: 'loc. pl.' },
  'kalpa': { meaning: 'wish-fulfilling / capable', grammar: 'adj./stem' },
  'vṛkṣa': { meaning: 'tree', grammar: 'stem' },
  'lakṣāvṛteṣu': { meaning: 'surrounded by hundreds of thousands', grammar: 'loc. pl.' },
  'surabhīr': { meaning: 'Surabhi cows', grammar: 'acc. pl.' },
  'abhipālayantam': { meaning: 'tending / herding', grammar: 'pres. part. acc.' },

  // ── Mantras & common prayers ──
  'hare': { meaning: 'O Hari! / O energy of the Lord!', grammar: 'voc.' },
  'rāma': { meaning: 'Rāma — source of all pleasure', grammar: 'voc.' },
  'oṁ': { meaning: 'the sacred syllable / the Absolute', grammar: 'indecl.' },
  'om': { meaning: 'the sacred syllable / the Absolute', grammar: 'indecl.' },
  'śrīla': { meaning: 'most beautiful / honored prefix', grammar: 'adj.' },
  'prabhupāda': { meaning: 'at whose feet masters take shelter', grammar: 'proper noun' },
  'tulasī': { meaning: 'sacred basil plant dear to Viṣṇu', grammar: 'proper noun' },
  'nṛsiṁha': { meaning: 'Lord Narasiṁha (half-man, half-lion)', grammar: 'proper noun' },
  'nṛsiṁhadeva': { meaning: 'Lord Nṛsiṁhadeva', grammar: 'proper noun' },
  'dāmodara': { meaning: 'Lord Dāmodara (bound by the belly rope)', grammar: 'proper noun' },
  'gaura': { meaning: 'golden (Caitanya Mahāprabhu)', grammar: 'adj./noun' },
  'nitāi': { meaning: 'Lord Nityānanda', grammar: 'proper noun' },
  'nityānanda': { meaning: 'eternal bliss / Lord Nityānanda', grammar: 'proper noun' },
  'caitanya': { meaning: 'consciousness / Lord Caitanya', grammar: 'noun/proper noun' },
  'mahāprabhu': { meaning: 'the great master', grammar: 'proper noun' },
  'viṣṇu': { meaning: 'the all-pervading Lord', root: '√viś (to enter)', grammar: 'proper noun' },
  'hari': { meaning: 'the Lord who removes ignorance', root: '√hṛ (to take away)' },
  'hariḥ': { meaning: 'Lord Hari', grammar: 'nom. sg.' },

  // ── Common compound parts ──
  'upahṛtam': { meaning: 'offered / presented', root: 'upa + √hṛ', grammar: 'past part.' },
  'samarpayitum': { meaning: 'to offer / to bestow', root: 'sam + √ṛ', grammar: 'infinitive' },
  'unnatojjvala': { meaning: 'elevated and brilliant', grammar: 'compound adj.' },
  'rasāṁ': { meaning: 'taste / mellow / relationship', grammar: 'acc. sg.' },
  'rasam': { meaning: 'taste / mellow', grammar: 'acc. sg.' },
  'rasa': { meaning: 'spiritual taste / mellow', grammar: 'stem' },
  'śriyam': { meaning: 'beauty / opulence', grammar: 'acc. sg.' },
  'puraṭa': { meaning: 'gold', grammar: 'stem' },
  'dyuti': { meaning: 'effulgence / brilliance', grammar: 'stem' },
  'kadamba': { meaning: 'kadamba tree / multitude', grammar: 'stem' },
  'sandīpitaḥ': { meaning: 'illuminated / inflamed', grammar: 'nom. sg. past part.' },
  'sadā': { meaning: 'always', grammar: 'adv.' },
  'kandare': { meaning: 'in the cave/core', grammar: 'loc. sg.' },
  'sphuratu': { meaning: 'may it manifest!', root: '√sphur', grammar: '3rd sg. imperative' },
  'vaḥ': { meaning: 'your (all)', grammar: 'gen. pl.' },
  'nandanaḥ': { meaning: 'son / one who gives bliss', grammar: 'nom. sg.' },
  'śacī': { meaning: 'Śacī (mother of Lord Caitanya)', grammar: 'proper noun' },
  'anarpita': { meaning: 'not previously given', grammar: 'past part.' },
  'carīṁ': { meaning: 'practice / conduct', grammar: 'acc. sg.' },
  'cirāt': { meaning: 'for a long time', grammar: 'abl.' },

  // ── Numbers ──
  'eka': { meaning: 'one', grammar: 'num.' },
  'dvi': { meaning: 'two', grammar: 'num.' },
  'tri': { meaning: 'three', grammar: 'num.' },
  'catur': { meaning: 'four', grammar: 'num.' },
}

// Common Sanskrit dhātus (verbal roots) for reference
export const DHATU_ROOTS: { root: string; meaning: string; examples: string[] }[] = [
  { root: '√bhaj', meaning: 'to serve / worship', examples: ['bhakti', 'bhakta', 'bhajāmi'] },
  { root: '√kṛ', meaning: 'to do / make', examples: ['karma', 'kṛṣṇa', 'namaskuru'] },
  { root: '√jñā', meaning: 'to know', examples: ['jñāna', 'jānāti', 'vijñāna'] },
  { root: '√bhū', meaning: 'to be / become', examples: ['bhava', 'bhavati', 'sambhavāmi'] },
  { root: '√dhṛ', meaning: 'to hold / sustain', examples: ['dharma', 'dhāraṇā'] },
  { root: '√yuj', meaning: 'to yoke / unite', examples: ['yoga', 'yukta', 'yuñjan'] },
  { root: '√vid', meaning: 'to know / find', examples: ['veda', 'vidyā', 'vedānta'] },
  { root: '√nam', meaning: 'to bow / prostrate', examples: ['namaḥ', 'namāmi', 'namo'] },
  { root: '√hṛ', meaning: 'to take away / steal', examples: ['hari', 'harati'] },
  { root: '√śru', meaning: 'to hear / listen', examples: ['śruti', 'śravaṇam'] },
  { root: '√man', meaning: 'to think / consider', examples: ['mantra', 'manas', 'matvā'] },
  { root: '√div', meaning: 'to shine / play', examples: ['deva', 'divya', 'dīpta'] },
  { root: '√muc', meaning: 'to free / release', examples: ['mokṣa', 'mukti', 'vimukta'] },
  { root: '√budh', meaning: 'to know / awaken', examples: ['buddhi', 'bodha', 'buddha'] },
  { root: '√śās', meaning: 'to instruct / rule', examples: ['śāstra', 'anuśāsana'] },
  { root: '√vṛt', meaning: 'to exist / turn', examples: ['vṛtti', 'pravartate'] },
  { root: '√pad', meaning: 'to go / fall', examples: ['pada', 'prapadyate'] },
  { root: '√sthā', meaning: 'to stand / stay', examples: ['sthiti', 'sthāna', 'pratiṣṭhā'] },
  { root: '√ji', meaning: 'to conquer', examples: ['jaya', 'jayati', 'vijaya'] },
  { root: '√dṛś', meaning: 'to see', examples: ['darśana', 'paśyati', 'dṛṣṭi'] },
  { root: '√vac', meaning: 'to speak', examples: ['vāc', 'vacana', 'uvāca'] },
  { root: '√gam', meaning: 'to go', examples: ['āgama', 'gacchati'] },
  { root: '√mā', meaning: 'to measure / create', examples: ['māyā', 'nirmāṇa'] },
  { root: '√viś', meaning: 'to enter / pervade', examples: ['viṣṇu', 'viśva'] },
]

// Look up a word, trying various normalizations
export function lookupWord(word: string): GlossaryEntry | null {
  const raw = word.toLowerCase().trim()

  // Direct match
  if (glossary[raw]) return glossary[raw]

  // Strip leading/trailing hyphens (compound separators)
  const stripped = raw.replace(/^-+|-+$/g, '')
  if (glossary[stripped]) return glossary[stripped]

  // Try without trailing visarga/anusvāra
  const noFinal = stripped.replace(/[ḥṁṃ]$/, '')
  if (glossary[noFinal]) return glossary[noFinal]

  // Try stem (remove common endings)
  for (const suffix of ['āḥ', 'aḥ', 'am', 'aṁ', 'āṁ', 'ān', 'āni', 'ena', 'āya', 'āt', 'asya', 'eṣu', 'aiḥ', 'ābhiḥ']) {
    if (stripped.endsWith(suffix) && stripped.length > suffix.length + 1) {
      const stem = stripped.slice(0, -suffix.length)
      if (glossary[stem]) return glossary[stem]
      if (glossary[stem + 'a']) return glossary[stem + 'a']
    }
  }

  return null
}
