export type Difficulty = 'easy' | 'easy-medium' | 'medium' | 'medium-hard' | 'hard'
export type Meter = 'anushtubh' | 'trishtubh' | 'jagati' | 'vasanta_tilaka' | 'longer' | 'mantra'

export interface SlokaEntry {
  id: string
  text: string
  reference: string
  source: string
  translation: string
  meter: Meter
  difficulty: Difficulty
  group?: string  // groups multi-verse bhajans, e.g. 'gurvastakam' — all entries with same group can be added at once
}

// Difficulty = PRONUNCIATION complexity (dynamic user scoring overlays this)
export const slokaLibrary: SlokaEntry[] = [

  // ══════ BHAGAVAD-GĪTĀ (anuṣṭubh) ══════

  // Easy
  { id:'bg-10.8', meter:'anushtubh', difficulty:'easy', source:'Bhagavad-gītā', reference:'BG 10.8', text:`ahaṁ sarvasya prabhavo\nmattaḥ sarvaṁ pravartate\niti matvā bhajante māṁ\nbudhā bhāva-samanvitāḥ`, translation:'I am the source of all. Everything emanates from Me. The wise worship Me with devotion.' },
  { id:'bg-9.26', meter:'anushtubh', difficulty:'easy', source:'Bhagavad-gītā', reference:'BG 9.26', text:`patraṁ puṣpaṁ phalaṁ toyaṁ\nyo me bhaktyā prayacchati\ntad ahaṁ bhakty-upahṛtam\naśnāmi prayatātmanaḥ`, translation:'A leaf, flower, fruit, water — if offered with devotion, I accept it.' },
  { id:'bg-9.34', meter:'anushtubh', difficulty:'easy', source:'Bhagavad-gītā', reference:'BG 9.34', text:`man-manā bhava mad-bhakto\nmad-yājī māṁ namaskuru\nmām evaiṣyasi yuktvaivam\nātmānaṁ mat-parāyaṇaḥ`, translation:'Always think of Me, become My devotee, worship Me and offer obeisances.' },
  { id:'bg-7.7', meter:'anushtubh', difficulty:'easy', source:'Bhagavad-gītā', reference:'BG 7.7', text:`mattaḥ parataraṁ nānyat\nkiñcid asti dhanañjaya\nmayi sarvam idaṁ protaṁ\nsūtre maṇi-gaṇā iva`, translation:'There is no truth superior to Me. Everything rests upon Me, as pearls on a thread.' },
  { id:'bg-7.19', meter:'anushtubh', difficulty:'easy', source:'Bhagavad-gītā', reference:'BG 7.19', text:`bahūnāṁ janmanām ante\njñānavān māṁ prapadyate\nvāsudevaḥ sarvam iti\nsa mahātmā su-durlabhaḥ`, translation:'After many births, the wise surrender unto Me. Such a great soul is very rare.' },
  { id:'bg-12.8', meter:'anushtubh', difficulty:'easy', source:'Bhagavad-gītā', reference:'BG 12.8', text:`mayy eva mana ādhatsva\nmayi buddhiṁ niveśaya\nnivasiṣyasi mayy eva\nata ūrdhvaṁ na saṁśayaḥ`, translation:'Fix your mind and intelligence upon Me. You will live in Me always, without doubt.' },
  { id:'bg-4.11', meter:'anushtubh', difficulty:'easy', source:'Bhagavad-gītā', reference:'BG 4.11', text:`ye yathā māṁ prapadyante\ntāṁs tathaiva bhajāmy aham\nmama vartmānuvartante\nmanuṣyāḥ pārtha sarvaśaḥ`, translation:'As they surrender unto Me, I reward them accordingly.' },

  // Easy-Medium
  { id:'bg-4.8', meter:'anushtubh', difficulty:'easy-medium', source:'Bhagavad-gītā', reference:'BG 4.8', text:`paritrāṇāya sādhūnāṁ\nvināśāya ca duṣkṛtām\ndharma-saṁsthāpanārthāya\nsambhavāmi yuge yuge`, translation:'To protect the pious and annihilate the wicked, I appear millennium after millennium.' },
  { id:'bg-18.66', meter:'anushtubh', difficulty:'easy-medium', source:'Bhagavad-gītā', reference:'BG 18.66', text:`sarva-dharmān parityajya\nmām ekaṁ śaraṇaṁ vraja\nahaṁ tvāṁ sarva-pāpebhyo\nmokṣayiṣyāmi mā śucaḥ`, translation:'Abandon all dharmas and surrender unto Me. I shall deliver you from all sins.' },
  { id:'bg-9.22', meter:'anushtubh', difficulty:'easy-medium', source:'Bhagavad-gītā', reference:'BG 9.22', text:`ananyāś cintayanto māṁ\nye janāḥ paryupāsate\nteṣāṁ nityābhiyuktānāṁ\nyoga-kṣemaṁ vahāmy aham`, translation:'For those who worship Me with exclusive devotion, I carry what they lack and preserve what they have.' },
  { id:'bg-8.7', meter:'anushtubh', difficulty:'easy-medium', source:'Bhagavad-gītā', reference:'BG 8.7', text:`tasmāt sarveṣu kāleṣu\nmām anusmara yudhya ca\nmayy arpita-mano-buddhir\nmām evaiṣyasy asaṁśayaḥ`, translation:'Always remember Me and fight. With mind and intelligence fixed on Me, you will come to Me.' },
  { id:'bg-15.15', meter:'anushtubh', difficulty:'easy-medium', source:'Bhagavad-gītā', reference:'BG 15.15', text:`sarvasya cāhaṁ hṛdi sanniviṣṭo\nmattaḥ smṛtir jñānam apohanaṁ ca\nvedaiś ca sarvair aham eva vedyo\nvedānta-kṛd veda-vid eva cāham`, translation:'I am seated in everyone\'s heart. From Me come remembrance, knowledge and forgetfulness.' },
  { id:'bg-6.47', meter:'anushtubh', difficulty:'easy-medium', source:'Bhagavad-gītā', reference:'BG 6.47', text:`yoginām api sarveṣāṁ\nmad-gatenāntarātmanā\nśraddhāvān bhajate yo māṁ\nsa me yuktatamo mataḥ`, translation:'Of all yogīs, the one with great faith who worships Me is the most intimately united with Me.' },

  // Medium
  { id:'bg-2.47', meter:'anushtubh', difficulty:'medium', source:'Bhagavad-gītā', reference:'BG 2.47', text:`karmaṇy evādhikāras te\nmā phaleṣu kadācana\nmā karma-phala-hetur bhūr\nmā te saṅgo 'stv akarmaṇi`, translation:'You have a right to perform your duty, but not to the fruits of action.' },
  { id:'bg-2.20', meter:'anushtubh', difficulty:'medium', source:'Bhagavad-gītā', reference:'BG 2.20', text:`na jāyate mriyate vā kadācin\nnāyaṁ bhūtvā bhavitā vā na bhūyaḥ\najo nityaḥ śāśvato 'yaṁ purāṇo\nna hanyate hanyamāne śarīre`, translation:'The soul is never born nor dies. It is unborn, eternal, ever-existing, and primeval.' },
  { id:'bg-3.21', meter:'anushtubh', difficulty:'medium', source:'Bhagavad-gītā', reference:'BG 3.21', text:`yad yad ācarati śreṣṭhas\ntat tad evetaro janaḥ\nsa yat pramāṇaṁ kurute\nlokas tad anuvartate`, translation:'Whatever a great man does, common men follow.' },
  { id:'bg-5.29', meter:'anushtubh', difficulty:'medium', source:'Bhagavad-gītā', reference:'BG 5.29', text:`bhoktāraṁ yajña-tapasāṁ\nsarva-loka-maheśvaram\nsuhṛdaṁ sarva-bhūtānāṁ\njñātvā māṁ śāntim ṛcchati`, translation:'Knowing Me as the enjoyer of sacrifice, the supreme lord and friend of all beings, one attains peace.' },
  { id:'bg-10.10', meter:'anushtubh', difficulty:'medium', source:'Bhagavad-gītā', reference:'BG 10.10', text:`teṣāṁ satata-yuktānāṁ\nbhajatāṁ prīti-pūrvakam\ndadāmi buddhi-yogaṁ taṁ\nyena mām upayānti te`, translation:'To those who worship Me with love, I give the understanding by which they can come to Me.' },
  { id:'bg-4.34', meter:'anushtubh', difficulty:'medium', source:'Bhagavad-gītā', reference:'BG 4.34', text:`tad viddhi praṇipātena\nparipraśnena sevayā\nupadekṣyanti te jñānaṁ\njñāninas tattva-darśinaḥ`, translation:'Learn the truth by approaching a spiritual master. Inquire submissively and render service.' },

  // Medium-Hard
  { id:'bg-4.7', meter:'anushtubh', difficulty:'medium-hard', source:'Bhagavad-gītā', reference:'BG 4.7', text:`yadā yadā hi dharmasya\nglānir bhavati bhārata\nabhyutthānam adharmasya\ntadātmānaṁ sṛjāmy aham`, translation:'Whenever there is a decline of dharma, I manifest Myself.' },
  { id:'bg-18.65', meter:'anushtubh', difficulty:'medium-hard', source:'Bhagavad-gītā', reference:'BG 18.65', text:`man-manā bhava mad-bhakto\nmad-yājī māṁ namaskuru\nmām evaiṣyasi satyaṁ te\npratijāne priyo 'si me`, translation:'Think of Me, be My devotee, worship Me — you will come to Me. I truly promise this.' },
  { id:'bg-2.62', meter:'anushtubh', difficulty:'medium-hard', source:'Bhagavad-gītā', reference:'BG 2.62', text:`dhyāyato viṣayān puṁsaḥ\nsaṅgas teṣūpajāyate\nsaṅgāt sañjāyate kāmaḥ\nkāmāt krodho 'bhijāyate`, translation:'Contemplating sense objects breeds attachment; from attachment lust develops; from lust anger arises.' },
  { id:'bg-9.2', meter:'anushtubh', difficulty:'medium-hard', source:'Bhagavad-gītā', reference:'BG 9.2', text:`rāja-vidyā rāja-guhyaṁ\npavitram idam uttamam\npratyakṣāvagamaṁ dharmyaṁ\nsu-sukhaṁ kartum avyayam`, translation:'This knowledge is the king of education, the most secret, purest, directly perceivable, and everlasting.' },

  // Hard
  { id:'bg-13.13', meter:'anushtubh', difficulty:'hard', source:'Bhagavad-gītā', reference:'BG 13.13', text:`jñeyaṁ yat tat pravakṣyāmi\nyaj jñātvāmṛtam aśnute\nanādi mat-paraṁ brahma\nna sat tan nāsad ucyate`, translation:'I shall explain the knowable, knowing which you will taste the eternal.' },
  { id:'bg-18.54', meter:'anushtubh', difficulty:'hard', source:'Bhagavad-gītā', reference:'BG 18.54', text:`brahma-bhūtaḥ prasannātmā\nna śocati na kāṅkṣati\nsamaḥ sarveṣu bhūteṣu\nmad-bhaktiṁ labhate parām`, translation:'One in the transcendental position realizes Brahman and achieves pure devotion unto Me.' },
  { id:'bg-8.5', meter:'anushtubh', difficulty:'hard', source:'Bhagavad-gītā', reference:'BG 8.5', text:`anta-kāle ca mām eva\nsmaran muktvā kalevaram\nyaḥ prayāti sa mad-bhāvaṁ\nyāti nāsty atra saṁśayaḥ`, translation:'Whoever remembers Me at death, leaving the body, attains My nature. No doubt.' },
  { id:'bg-11.55', meter:'anushtubh', difficulty:'hard', source:'Bhagavad-gītā', reference:'BG 11.55', text:`mat-karma-kṛn mat-paramo\nmad-bhaktaḥ saṅga-varjitaḥ\nnirvairaḥ sarva-bhūteṣu\nyaḥ sa mām eti pāṇḍava`, translation:'One who works for Me, free from attachment and enmity — he comes to Me.' },

  // ══════ ŚRĪMAD-BHĀGAVATAM ══════

  { id:'sb-1.2.6', meter:'anushtubh', difficulty:'medium', source:'Śrīmad-Bhāgavatam', reference:'ŚB 1.2.6', text:`sa vai puṁsāṁ paro dharmo\nyato bhaktir adhokṣaje\nahaituky apratihatā\nyayātmā suprasīdati`, translation:'The supreme dharma is causeless and uninterrupted devotion to the Lord.' },
  { id:'sb-1.2.11', meter:'anushtubh', difficulty:'medium-hard', source:'Śrīmad-Bhāgavatam', reference:'ŚB 1.2.11', text:`vadanti tat tattva-vidas\ntattvaṁ yaj jñānam advayam\nbrahmeti paramātmeti\nbhagavān iti śabdyate`, translation:'The Absolute Truth is known as Brahman, Paramātmā, and Bhagavān.' },
  { id:'sb-1.2.17', meter:'anushtubh', difficulty:'medium', source:'Śrīmad-Bhāgavatam', reference:'ŚB 1.2.17', text:`śṛṇvatāṁ sva-kathāḥ kṛṣṇaḥ\npuṇya-śravaṇa-kīrtanaḥ\nhṛdy antaḥ stho hy abhadrāṇi\nvidhunoti suhṛt satām`, translation:'Kṛṣṇa, seated within the heart, destroys inauspiciousness for those who hear about Him.' },
  { id:'sb-1.2.18', meter:'anushtubh', difficulty:'medium-hard', source:'Śrīmad-Bhāgavatam', reference:'ŚB 1.2.18', text:`naṣṭa-prāyeṣv abhadreṣu\nnityaṁ bhāgavata-sevayā\nbhagavaty uttama-śloke\nbhaktir bhavati naiṣṭhikī`, translation:'By regular Bhāgavatam study, all troubles are destroyed, and loving devotion is established.' },
  { id:'sb-1.3.28', meter:'anushtubh', difficulty:'easy-medium', source:'Śrīmad-Bhāgavatam', reference:'ŚB 1.3.28', text:`ete cāṁśa-kalāḥ puṁsaḥ\nkṛṣṇas tu bhagavān svayam\nindrāri-vyākulaṁ lokaṁ\nmṛḍayanti yuge yuge`, translation:'All incarnations are portions or portions of portions, but Kṛṣṇa is the Supreme Personality of Godhead Himself.' },
  { id:'sb-7.5.23', meter:'trishtubh', difficulty:'easy', source:'Śrīmad-Bhāgavatam', reference:'ŚB 7.5.23', text:`śravaṇaṁ kīrtanaṁ viṣṇoḥ\nsmaraṇaṁ pāda-sevanam\narcanaṁ vandanaṁ dāsyaṁ\nsakhyam ātma-nivedanam`, translation:'Hearing, chanting, remembering Viṣṇu, serving His feet, worshiping, praying, serving, friendship, and self-surrender.' },
  { id:'sb-7.5.32', meter:'trishtubh', difficulty:'medium-hard', source:'Śrīmad-Bhāgavatam', reference:'ŚB 7.5.32', text:`naiṣāṁ matis tāvad urukramāṅghriṁ\nspṛśaty anarthāpagamo yad-arthaḥ\nmahīyasāṁ pāda-rajo-'bhiṣekaṁ\nniṣkiñcanānāṁ na vṛṇīta yāvat`, translation:'One cannot understand the Lord until one receives the dust of the feet of great devotees.' },
  { id:'sb-3.25.25', meter:'trishtubh', difficulty:'medium', source:'Śrīmad-Bhāgavatam', reference:'ŚB 3.25.25', text:`satāṁ prasaṅgān mama vīrya-saṁvido\nbhavanti hṛt-karṇa-rasāyanāḥ kathāḥ\ntaj-joṣaṇād āśv apavarga-vartmani\nśraddhā ratir bhaktir anukramiṣyati`, translation:'In devotee association, discussions of My glories become pleasing; faith, attachment and devotion develop.' },
  { id:'sb-10.14.8', meter:'trishtubh', difficulty:'hard', source:'Śrīmad-Bhāgavatam', reference:'ŚB 10.14.8', text:`tat te 'nukampāṁ su-samīkṣamāṇo\nbhuñjāna evātma-kṛtaṁ vipākam\nhṛd-vāg-vapurbhir vidadhan namas te\njīveta yo mukti-pade sa dāya-bhāk`, translation:'One who awaits Your compassion while tolerating past karma is eligible for liberation.' },
  { id:'sb-10.51.53', meter:'jagati', difficulty:'easy-medium', source:'Śrīmad-Bhāgavatam', reference:'ŚB 10.51.53', text:`bhavāpavargo bhramato yadā bhavej\njanasya tarhy acyuta sat-samāgamaḥ\nsat-saṅgamo yarhi tadaiva sad-gatau\nparāvareśe tvayi jāyate matiḥ`, translation:'When liberation is due, a wandering soul gets devotee association, then devotion to You arises.' },
  { id:'sb-11.2.37', meter:'jagati', difficulty:'medium', source:'Śrīmad-Bhāgavatam', reference:'ŚB 11.2.37', text:`bhayaṁ dvitīyābhiniveśataḥ syād\nīśād apetasya viparyayo 'smṛtiḥ\ntan-māyayāto budha ābhajet taṁ\nbhaktyaikayeśaṁ guru-devatātmā`, translation:'Fear arises from turning away from the Lord. A wise person should worship Him with exclusive devotion.' },
  { id:'sb-11.5.32', meter:'jagati', difficulty:'medium-hard', source:'Śrīmad-Bhāgavatam', reference:'ŚB 11.5.32', text:`kṛṣṇa-varṇaṁ tviṣākṛṣṇaṁ\nsāṅgopāṅgāstra-pārṣadam\nyajñaiḥ saṅkīrtana-prāyair\nyajanti hi su-medhasaḥ`, translation:'Those with good intelligence worship the Lord who chants Kṛṣṇa\'s name through congregational chanting.' },
  { id:'sb-10.33.39', meter:'jagati', difficulty:'hard', source:'Śrīmad-Bhāgavatam', reference:'ŚB 10.33.39', text:`vikrīḍitaṁ vraja-vadhūbhir idaṁ ca viṣṇoḥ\nśraddhānvito 'nuśṛṇuyād atha varṇayed yaḥ\nbhaktiṁ parāṁ bhagavati pratilabhya kāmaṁ\nhṛd-rogam āśv apahinoty acireṇa dhīraḥ`, translation:'One who faithfully hears about Kṛṣṇa\'s pastimes with the gopīs attains supreme devotion and removes lust.' },
  { id:'sb-6.3.22', meter:'anushtubh', difficulty:'easy-medium', source:'Śrīmad-Bhāgavatam', reference:'ŚB 6.3.22', text:`etāvān eva loke 'smin\npuṁsāṁ dharmaḥ paraḥ smṛtaḥ\nbhakti-yogo bhagavati\ntan-nāma-grahaṇādibhiḥ`, translation:'The supreme dharma is devotional service beginning with chanting His holy names.' },
  { id:'sb-2.4.18', meter:'anushtubh', difficulty:'hard', source:'Śrīmad-Bhāgavatam', reference:'ŚB 2.4.18', text:`kirāta-hūṇāndhra-pulinda-pulkaśā\nābhīra-śumbhā yavanāḥ khasādayaḥ\nye 'nye ca pāpā yad-apāśrayāśrayāḥ\nśudhyanti tasmai prabhaviṣṇave namaḥ`, translation:'Even the most sinful can be purified by taking shelter of the Lord\'s devotees.' },
  { id:'sb-2.3.17', meter:'trishtubh', difficulty:'easy-medium', source:'Śrīmad-Bhāgavatam', reference:'ŚB 2.3.17', text:`āyur harati vai puṁsām\nudyann astaṁ ca yann asau\ntasyarte yat-kṣaṇo nīta\nuttama-śloka-vārtayā`, translation:'The sun diminishes everyone\'s life — except for those who use time discussing the Supreme Lord.' },
  { id:'sb-10.14.3', meter:'longer', difficulty:'hard', source:'Śrīmad-Bhāgavatam', reference:'ŚB 10.14.3', text:`jñāne prayāsam udapāsya namanta eva\njīvanti san-mukharitāṁ bhavadīya-vārtām\nsthāne sthitāḥ śruti-gatāṁ tanu-vāṅ-manobhir\nye prāyaśo 'jita jito 'py asi tais tri-lokyām`, translation:'Those who hear Your glories from devotees, remaining in their position, can conquer the unconquerable.' },

  // ══════ BRAHMA-SAṀHITĀ (vasanta-tilakā) ══════

  { id:'bs-5.1', meter:'vasanta_tilaka', difficulty:'easy-medium', source:'Brahma-saṁhitā', reference:'BS 5.1', text:`īśvaraḥ paramaḥ kṛṣṇaḥ\nsac-cid-ānanda-vigrahaḥ\nanādir ādir govindaḥ\nsarva-kāraṇa-kāraṇam`, translation:'Kṛṣṇa is the Supreme Godhead with an eternal blissful body. He is the cause of all causes.' },
  { id:'bs-5.29', meter:'vasanta_tilaka', difficulty:'medium', source:'Brahma-saṁhitā', reference:'BS 5.29', text:`cintāmaṇi-prakara-sadmasu kalpa-vṛkṣa-\nlakṣāvṛteṣu surabhīr abhipālayantam\nlakṣmī-sahasra-śata-sambhrama-sevyamānaṁ\ngovindam ādi-puruṣaṁ tam ahaṁ bhajāmi`, translation:'I worship Govinda who tends cows in abodes of cintāmaṇi, served by hundreds of thousands of Lakṣmīs.' },
  { id:'bs-5.30', meter:'vasanta_tilaka', difficulty:'medium', source:'Brahma-saṁhitā', reference:'BS 5.30', text:`veṇuṁ kvaṇantam aravinda-dalāyatākṣam-\nbarhāvataṁsam asitāmbuda-sundarāṅgam\nkandarpa-koṭi-kamanīya-viśeṣa-śobhaṁ\ngovindam ādi-puruṣaṁ tam ahaṁ bhajāmi`, translation:'I worship Govinda who plays the flute, with lotus eyes, peacock feather, beauty surpassing millions of Cupids.' },
  { id:'bs-5.31', meter:'vasanta_tilaka', difficulty:'medium-hard', source:'Brahma-saṁhitā', reference:'BS 5.31', text:`ālola-candraka-lasad-vanamālya-vaṁśī-\nratnāṅgadaṁ praṇaya-keli-kalā-vilāsam\nśyāmaṁ tri-bhaṅga-lalitaṁ niyata-prakāśaṁ\ngovindam ādi-puruṣaṁ tam ahaṁ bhajāmi`, translation:'I worship Govinda, adorned with garland, flute, jeweled armlets, standing in His three-fold bending form.' },
  { id:'bs-5.32', meter:'vasanta_tilaka', difficulty:'medium-hard', source:'Brahma-saṁhitā', reference:'BS 5.32', text:`aṅgāni yasya sakalendriya-vṛtti-manti\npaśyanti pānti kalayanti ciraṁ jaganti\nānanda-cin-maya-sad-ujjvala-vigrahasya\ngovindam ādi-puruṣaṁ tam ahaṁ bhajāmi`, translation:'I worship Govinda whose limbs can perform all functions, who eternally maintains all universes.' },
  { id:'bs-5.33', meter:'vasanta_tilaka', difficulty:'hard', source:'Brahma-saṁhitā', reference:'BS 5.33', text:`advaitam acyutam anādim ananta-rūpam\nādyaṁ purāṇa-puruṣaṁ nava-yauvanaṁ ca\nvedeṣu durlabham adurlabham ātma-bhaktau\ngovindam ādi-puruṣaṁ tam ahaṁ bhajāmi`, translation:'I worship Govinda — undivided, infallible, beginningless, with unlimited forms, the oldest yet always a fresh youth.' },
  { id:'bs-5.35', meter:'vasanta_tilaka', difficulty:'hard', source:'Brahma-saṁhitā', reference:'BS 5.35', text:`eko 'py asau racayituṁ jagad-aṇḍa-koṭiṁ\nyac-chaktir asti jagad-aṇḍa-cayā yad-antaḥ\naṇḍāntara-stha-paramāṇu-cayāntara-sthaṁ\ngovindam ādi-puruṣaṁ tam ahaṁ bhajāmi`, translation:'I worship Govinda who enters each universe and every atom by one plenary portion.' },
  { id:'bs-5.38', meter:'vasanta_tilaka', difficulty:'medium', source:'Brahma-saṁhitā', reference:'BS 5.38', text:`premāñjana-cchurita-bhakti-vilocanena\nsantaḥ sadaiva hṛdayeṣu vilokayanti\nyaṁ śyāmasundaram acintya-guṇa-svarūpaṁ\ngovindam ādi-puruṣaṁ tam ahaṁ bhajāmi`, translation:'I worship Govinda whom devotees always see in their hearts with eyes anointed with the ointment of love.' },
  { id:'bs-5.40', meter:'vasanta_tilaka', difficulty:'easy', source:'Brahma-saṁhitā', reference:'BS 5.40', text:`yasya prabhā prabhavato jagad-aṇḍa-koṭi-\nkoṭiṣv aśeṣa-vasudhādi-vibhūti-bhinnam\ntad brahma niṣkalam anantam aśeṣa-bhūtaṁ\ngovindam ādi-puruṣaṁ tam ahaṁ bhajāmi`, translation:'I worship Govinda whose effulgence is the source of the Brahman containing millions of universes.' },

  // ══════ CAITANYA-CARITĀMṚTA & ŚIKṢĀṢṬAKA ══════

  { id:'cc-adi-1.4', meter:'longer', difficulty:'medium-hard', source:'Caitanya-caritāmṛta', reference:'CC Ādi 1.4', text:`anarpita-carīṁ cirāt karuṇayāvatīrṇaḥ kalau\nsamarpayitum unnatojjvala-rasāṁ sva-bhakti-śriyam\nhariḥ puraṭa-sundara-dyuti-kadamba-sandīpitaḥ\nsadā hṛdaya-kandare sphuratu vaḥ śacī-nandanaḥ`, translation:'May the Lord who descended in Kali-yuga to bestow the most elevated devotion always manifest in your hearts.' },
  { id:'sa-1', meter:'longer', difficulty:'hard', source:'Śikṣāṣṭaka', reference:'Śikṣāṣṭaka 1', text:`ceto-darpaṇa-mārjanaṁ bhava-mahā-dāvāgni-nirvāpaṇaṁ\nśreyaḥ-kairava-candrikā-vitaraṇaṁ vidyā-vadhū-jīvanam\nānandāmbudhi-vardhanaṁ prati-padaṁ pūrṇāmṛtāsvādanaṁ\nsarvātma-snapanaṁ paraṁ vijayate śrī-kṛṣṇa-saṅkīrtanam`, translation:'All victory for the chanting of Śrī Kṛṣṇa which cleanses the mirror of the heart.' },
  { id:'sa-2', meter:'longer', difficulty:'medium', source:'Śikṣāṣṭaka', reference:'Śikṣāṣṭaka 2', text:`nāmnām akāri bahudhā nija-sarva-śaktis\ntatrārpitā niyamitaḥ smaraṇe na kālaḥ\netādṛśī tava kṛpā bhagavan mamāpi\ndurdaivam īdṛśam ihājani nānurāgaḥ`, translation:'O Lord, Your holy name bestows all auspiciousness. Yet my misfortune is that I have no attraction.' },
  { id:'sa-3', meter:'anushtubh', difficulty:'medium-hard', source:'Śikṣāṣṭaka', reference:'Śikṣāṣṭaka 3', text:`tṛṇād api sunīcena\ntaror api sahiṣṇunā\namāninā mānadena\nkīrtanīyaḥ sadā hariḥ`, translation:'One should be humbler than a blade of grass, more tolerant than a tree. In such a state one can chant constantly.' },
  { id:'sa-8', meter:'longer', difficulty:'medium', source:'Śikṣāṣṭaka', reference:'Śikṣāṣṭaka 8', text:`āśliṣya vā pāda-ratāṁ pinaṣṭu mām\nadarśanān marma-hatāṁ karotu vā\nyathā tathā vā vidadhātu lampaṭo\nmat-prāṇa-nāthas tu sa eva nāparaḥ`, translation:'Let Kṛṣṇa embrace me or trample me — He is the Lord of my life.' },

  // ══════ ĪŚOPANIṢAD ══════

  { id:'iso-1', meter:'anushtubh', difficulty:'medium', source:'Īśopaniṣad', reference:'Īśo 1', text:`īśāvāsyam idaṁ sarvaṁ\nyat kiñca jagatyāṁ jagat\ntena tyaktena bhuñjīthā\nmā gṛdhaḥ kasya svid dhanam`, translation:'Everything belongs to the Lord. One should accept only what one needs and not covet others\' property.' },

  // ══════ MANTRAS & CHANTS ══════

  { id:'man-e1', meter:'mantra', difficulty:'easy', source:'Mahā-mantra', reference:'Hare Kṛṣṇa Mahā-mantra', text:`hare kṛṣṇa hare kṛṣṇa\nkṛṣṇa kṛṣṇa hare hare\nhare rāma hare rāma\nrāma rāma hare hare`, translation:'The great chant for deliverance.' },
  { id:'man-e2', meter:'mantra', difficulty:'easy', source:'Praṇāma Mantra', reference:'Oṁ namo bhagavate vāsudevāya', text:`oṁ namo bhagavate vāsudevāya`, translation:'I offer my obeisances to the Supreme Lord Vāsudeva.' },
  { id:'man-e3', meter:'mantra', difficulty:'easy', source:'Pañca-tattva Mahā-mantra', reference:'Pañca-tattva Mantra', text:`jaya śrī-kṛṣṇa-caitanya\nprabhu nityānanda\nśrī-advaita gadādhara\nśrīvāsādi-gaura-bhakta-vṛnda`, translation:'Glory to Lord Caitanya, Prabhu Nityānanda, Śrī Advaita, Gadādhara, and all devotees of Lord Gaura.' },
  { id:'man-e4', meter:'mantra', difficulty:'easy', source:'Praṇāma', reference:'Haribol', text:`haribol haribol haribol`, translation:'Chant the name of Hari!' },
  { id:'man-e5', meter:'mantra', difficulty:'easy', source:'Nṛsiṁha Praṇāma', reference:'Nṛsiṁha Praṇāma', text:`namas te narasiṁhāya\nprahlādāhlāda-dāyine\nhiraṇyakaśipor vakṣaḥ-\nśilā-ṭaṅka-nakhālaye`, translation:'Obeisances to Lord Narasiṁha, who gives joy to Prahlāda.' },
  { id:'man-em1', meter:'mantra', difficulty:'easy-medium', source:'Prabhupāda Praṇāma', reference:'Guru Praṇāma', text:`nama oṁ viṣṇu-pādāya kṛṣṇa-preṣṭhāya bhū-tale\nśrīmate bhaktivedānta-svāmin iti nāmine\nnamas te sārasvate deve gaura-vāṇī-pracāriṇe\nnirviśeṣa-śūnyavādi-pāścātya-deśa-tāriṇe`, translation:'Obeisances to Śrīla Prabhupāda, delivering the Western countries.' },
  { id:'man-em2', meter:'mantra', difficulty:'easy-medium', source:'Tulasī Āratī', reference:'Tulasī Praṇāma', text:`vṛndāyai tulasī-devyai\npriyāyai keśavasya ca\nkṛṣṇa-bhakti-prade devī\nsatyavatyai namo namaḥ`, translation:'Obeisances to Tulasī-devī, who bestows devotion to Kṛṣṇa.' },
  { id:'man-em3', meter:'mantra', difficulty:'easy-medium', source:'Bhaktivinoda Ṭhākura', reference:'Jīv Jāgo', text:`jīv jāgo jīv jāgo gauracānda bole\nkota nidrā jāo māyā-piśācīra kole`, translation:'Wake up sleeping souls! How long will you sleep in the lap of Māyā?' },
  { id:'man-m1', meter:'mantra', difficulty:'medium', source:'Śrī Guru Praṇāma', reference:'Guru Vandanā', text:`oṁ ajñāna-timirāndhasya\njñānāñjana-śalākayā\ncakṣur unmīlitaṁ yena\ntasmai śrī-gurave namaḥ`, translation:'My spiritual master opened my eyes with the torch of knowledge.' },
  { id:'man-m2', meter:'mantra', difficulty:'medium', source:'Gāyatrī', reference:'Brahma-gāyatrī', text:`oṁ bhūr bhuvaḥ svaḥ\ntat savitur vareṇyaṁ\nbhargo devasya dhīmahi\ndhiyo yo naḥ pracodayāt`, translation:'Let us meditate upon the glorious effulgence of the divine creator.' },
  { id:'man-m3', meter:'mantra', difficulty:'medium', source:'Nṛsiṁha Prayers', reference:'Nṛsiṁha Kavacha', text:`ito nṛsiṁhaḥ parato nṛsiṁho\nyato yato yāmi tato nṛsiṁhaḥ\nbahir nṛsiṁho hṛdaye nṛsiṁho\nnṛsiṁham ādiṁ śaraṇaṁ prapadye`, translation:'Lord Nṛsiṁha is here and there, wherever I go. I surrender to that primeval Lord.' },
  { id:'man-mh1', meter:'mantra', difficulty:'medium-hard', source:'Dāmodarāṣṭaka', reference:'Dāmodarāṣṭaka 1', group:'damodarastaka', text:`namāmīśvaraṁ sac-cid-ānanda-rūpaṁ\nlasat-kuṇḍalaṁ gokule bhrājamanam\nyaśodā-bhiyolūkhalād dhāvamānaṁ\nparāmṛṣṭam atyantato drutya gopyā`, translation:'I bow to the Supreme Lord in bliss form, fleeing from the mortar in Gokula, caught by Yaśodā.' },
  { id:'man-mh2', meter:'mantra', difficulty:'medium-hard', source:'Gurv-aṣṭaka', reference:'Gurv-aṣṭaka 1', group:'gurvastakam', text:`saṁsāra-dāvānala-līḍha-loka-\ntrāṇāya kāruṇya-ghanāghanatvam\nprāptasya kalyāṇa-guṇārṇavasya\nvande guroḥ śrī-caraṇāravindam`, translation:'The guru, an ocean of auspicious qualities, appeared out of compassion to deliver the burning world.' },

  // ══════ ISKCON BHAJANS ══════

  // Bhaktivinoda Ṭhākura
  { id:'bj-1', meter:'mantra', difficulty:'easy', source:'Bhaktivinoda Ṭhākura', reference:'Gurudeva! (1)', text:`gurudeva!\nkṛpā-bindu diyā koro' ei dāse\ntṛṇāpekhā ati hīna\nsakala sahane bala diyā koro'\nnija-māne spṛhā-hīna`, translation:'O Gurudeva! Give just a drop of mercy. Make me humbler than a blade of grass and give me strength to bear all trials.' },
  { id:'bj-2', meter:'mantra', difficulty:'easy', source:'Bhaktivinoda Ṭhākura', reference:'Jaya Rādhā-Mādhava', text:`jaya rādhā-mādhava jaya kuñja-bihārī\njaya gopī-jana-vallabha jaya giri-vara-dhārī\nyaśodā-nandana braja-jana-raṇjana\nyamunā-tīra-vana-cārī`, translation:'All glories to Rādhā-Mādhava, the enjoyer of the groves, the lifter of Govardhana, the son of Yaśodā who wanders along the Yamunā.' },
  { id:'bj-3', meter:'mantra', difficulty:'easy-medium', source:'Bhaktivinoda Ṭhākura', reference:'Śrī Nāma (Harer nāma)', text:`harer nāma harer nāma\nharer nāmaiva kevalam\nkalau nāsty eva nāsty eva\nnāsty eva gatir anyathā`, translation:'In this age of Kali there is no other means of spiritual progress than the chanting of the holy name.' },
  { id:'bj-4', meter:'mantra', difficulty:'medium', source:'Bhaktivinoda Ṭhākura', reference:'Kabe Habe Bolo (1)', text:`kabe ha'be bolo se-dina āmār\naparādha ghuci' śuddha nāme ruci\nkṛpā-bale ha'be hṛdoye sañcār`, translation:'When, oh when will that day be mine? When will my offenses end and a taste for the pure holy name arise in my heart?' },
  { id:'bj-5', meter:'mantra', difficulty:'easy', source:'Bhaktivinoda Ṭhākura', reference:'Bhaja Hu Re Mana (1)', text:`bhaja hu re mana śrī-nanda-nandana\nabhaya-caraṇāravinda re\ndurlapha mānava-janama sat-saṅge\ntaroho e bhava-sindhu re`, translation:'O mind, worship the son of Nanda whose lotus feet grant fearlessness. This rare human life, in good association, can cross the ocean of birth and death.' },
  { id:'bj-6', meter:'mantra', difficulty:'medium', source:'Bhaktivinoda Ṭhākura', reference:'Jīv Jāgo (full)', text:`jīv jāgo jīv jāgo gauracānda bole\nkota nidrā jāo māyā-piśācīra kole\nbhajibo boliyā ese saṁsāra-bhitore\nbhuliyā rohile tumi avidyāra bhore`, translation:'Lord Gauracānda says: Wake up! How long will you sleep in Māyā\'s lap? You came to this world saying you would worship, but you forgot in the darkness of ignorance.' },
  { id:'bj-7', meter:'mantra', difficulty:'medium-hard', source:'Bhaktivinoda Ṭhākura', reference:'Ātma-nivedana (1)', text:`mānasa deho geho jo kichu mor\narpiluṅ tuwā pade nanda-kiśor\nsampade vipade jīvane-maraṇe\ndāy mama gelā tuwā o-pada varaṇe`, translation:'Mind, body, home — whatever I have I surrender at Your feet, O Nanda-kiśora. In good fortune or misfortune, life or death, I have accepted Your lotus feet.' },

  // Narottama dāsa Ṭhākura
  { id:'bj-8', meter:'mantra', difficulty:'easy-medium', source:'Narottama dāsa Ṭhākura', reference:'Hari Hari Biphale (1)', text:`hari hari biphale janama goṅāinu\nmanuṣya-janama pāiyā rādhā-kṛṣṇa nā bhajiyā\njāniyā śuniyā biṣa khāinu`, translation:'O Lord Hari, I have wasted my life! Obtaining a human birth, I failed to worship Rādhā-Kṛṣṇa and have knowingly drunk poison.' },
  { id:'bj-9', meter:'mantra', difficulty:'medium', source:'Narottama dāsa Ṭhākura', reference:'Gaurāṅga Bolite Habe (1)', text:`gaurāṅga bolite habe pulaka śarīra\nhari hari bolite nayane ba'be nīra\nāra kabe nitāicā̃da koruṇā koribe\nsaṁsāra-bāsanā mora kabe tuccha habe`, translation:'When will my body thrill at the name of Gaurāṅga? When will tears flow from my eyes at the name of Hari?' },
  { id:'bj-10', meter:'mantra', difficulty:'easy', source:'Narottama dāsa Ṭhākura', reference:'Śrī Rūpa Mañjarī Pada (1)', text:`śrī-rūpa-mañjarī-pada sei mora sampada\nsei mora bhajana-pūjana\nsei mora prāṇa-dhana sei mora ābharaṇa\nsei mora jīvanera jīvana`, translation:'The lotus feet of Śrī Rūpa Mañjarī are my treasure, my worship, my wealth, my ornament, and the life of my life.' },
  { id:'bj-11', meter:'mantra', difficulty:'easy-medium', source:'Narottama dāsa Ṭhākura', reference:'Sapārṣada (Hari Haraye Namaḥ)', text:`hari haraye namaḥ kṛṣṇa yādavāya namaḥ\nyādavāya mādhavāya keśavāya namaḥ\ngopāla govinda rāma śrī-madhusūdana\ngiridharī gopīnātha madana-mohana`, translation:'I offer my obeisances to Hari, Kṛṣṇa, Yādava, Mādhava, Keśava — Gopāla, Govinda, Rāma, Madhusūdana, Giridharī, Gopīnātha, Madana-mohana.' },

  // Śrīla Viśvanātha Cakravartī Ṭhākura
  { id:'bj-12', meter:'mantra', difficulty:'medium-hard', source:'Gurv-aṣṭaka', reference:'Gurv-aṣṭaka 2', group:'gurvastakam', text:`mahāprabhoḥ kīrtana-nṛtya-gīta-\nvāditra-mādyan-manaso rasena\nromāñca-kampāśru-taraṅga-bhājo\nvande guroḥ śrī-caraṇāravindam`, translation:'The guru is always chanting, dancing, and playing instruments, overwhelmed by ecstasy. I worship his lotus feet.' },
  { id:'bj-13', meter:'mantra', difficulty:'medium-hard', source:'Gurv-aṣṭaka', reference:'Gurv-aṣṭaka 7', group:'gurvastakam', text:`sākṣād-dharitvena samasta-śāstrair\nuktas tathā bhāvyata eva sadbhiḥ\nkintu prabhor yaḥ priya eva tasya\nvande guroḥ śrī-caraṇāravindam`, translation:'The guru is worshipped as the direct manifestation of the Lord, yet he is most dear to the Lord. I worship his lotus feet.' },

  // Popular kīrtana refrains
  { id:'bj-14', meter:'mantra', difficulty:'easy', source:'Kīrtana', reference:'Nitāi-Gaura Nām', text:`nitāi-gaura hari bol\nhari bol hari bol hari bol\nnitāi-gaura hari bol\nhari bol hari bol hari bol`, translation:'Chant the names of Nitāi and Gaura! Chant the name of Hari!' },
  { id:'bj-15', meter:'mantra', difficulty:'easy', source:'Kīrtana', reference:'Govinda Jaya Jaya', text:`govinda jaya jaya gopāla jaya jaya\nrādhā-ramaṇa hari govinda jaya jaya`, translation:'All glories to Govinda! All glories to Gopāla! All glories to Hari, the lover of Rādhā!' },
  { id:'bj-16', meter:'mantra', difficulty:'easy', source:'Kīrtana', reference:'Rādhe Rādhe Govinda', text:`rādhe rādhe rādhe rādhe\ngovinda govinda\nrādhe rādhe rādhe rādhe\ngovinda govinda`, translation:'Rādhe Rādhe! Govinda Govinda! A beloved kīrtana refrain.' },
  { id:'bj-17', meter:'mantra', difficulty:'easy-medium', source:'Kīrtana', reference:'Parama Koruṇa', text:`parama koruṇa pahū dui jana\nnitāi gauracandra\nsaba avatāra-sāra śiromaṇi\nkevala ānanda-kanda`, translation:'The two most merciful Lords are Nitāi and Gauracandra. Of all incarnations, They are the essence, the crest-jewels, the root of pure bliss.' },

  // Āratī songs
  { id:'bj-18', meter:'mantra', difficulty:'medium', source:'Bhaktivinoda Ṭhākura', reference:'Gaura Āratī (1)', text:`kiba jaya jaya gorācā̃der āratiko śobhā\njāhnavī-taṭa-vane jaga-mana-lobhā\ngaurāṅger āratik śobhā jaga-jana-mana-lobhā`, translation:'All glories to the beautiful āratī ceremony of Lord Caitanya on the bank of the Jāhnavī. It captivates the minds of all.' },
  { id:'bj-19', meter:'mantra', difficulty:'medium', source:'Śrīla Prabhupāda', reference:'Jaya Rādhā-Mādhava (Āratī)', text:`jaya rādhā-mādhava kuñja-bihārī\ngopī-jana-vallabha giri-vara-dhārī\nyaśodā-nandana braja-jana-raṇjana\nyamunā-tīra-vana-cārī\nrāsa-raseshvara dhira samira mandira bansibata\nrati-rasa-vasheshvara`, translation:'All glories to Rādhā-Mādhava, the enjoyer of Vṛndāvana, lifter of Govardhana, son of Yaśodā, Lord of the rāsa dance.' },

  // Śrīla Rūpa Gosvāmī
  { id:'bj-20', meter:'mantra', difficulty:'medium-hard', source:'Rūpa Gosvāmī', reference:'Namaḥ Mahā-vadānyāya', text:`namo mahā-vadānyāya\nkṛṣṇa-prema-pradāya te\nkṛṣṇāya kṛṣṇa-caitanya-\nnāmne gaura-tviṣe namaḥ`, translation:'I bow to the most munificent incarnation, who freely gives love of Kṛṣṇa — to Lord Kṛṣṇa Himself, appearing with a golden complexion as Kṛṣṇa Caitanya.' },

  // ══════ COMPLETE GURV-AṢṬAKA (missing verses 3-6, 8) ══════

  { id:'ga-3', meter:'mantra', difficulty:'medium-hard', source:'Gurv-aṣṭaka', reference:'Gurv-aṣṭaka 3', group:'gurvastakam', text:`śrī-vigrahārādhana-nitya-nānā-\nśṛṅgāra-tan-mandira-mārjanādau\nyuktasya bhaktāṁś ca niyuñjato 'pi\nvande guroḥ śrī-caraṇāravindam`, translation:'The guru is always engaged in decorating the Deity and engaging his disciples in temple service. I worship his lotus feet.' },
  { id:'ga-4', meter:'mantra', difficulty:'medium-hard', source:'Gurv-aṣṭaka', reference:'Gurv-aṣṭaka 4', group:'gurvastakam', text:`catur-vidha-śrī-bhagavat-prasāda-\nsvādv-anna-tṛptān hari-bhakta-saṅghān\nkṛtvaiva tṛptiṁ bhajataḥ sadaiva\nvande guroḥ śrī-caraṇāravindam`, translation:'The guru is always satisfied seeing devotees enjoy the four kinds of prasādam. I worship his lotus feet.' },
  { id:'ga-5', meter:'mantra', difficulty:'medium-hard', source:'Gurv-aṣṭaka', reference:'Gurv-aṣṭaka 5', group:'gurvastakam', text:`śrī-rādhikā-mādhavayor apāra-\nmādhurya-līlā-guṇa-rūpa-nāmnām\nprati-kṣaṇāsvādana-lolupasya\nvande guroḥ śrī-caraṇāravindam`, translation:'The guru always relishes the unlimited sweet pastimes, qualities, forms and names of Rādhā-Mādhava. I worship his lotus feet.' },
  { id:'ga-6', meter:'mantra', difficulty:'medium-hard', source:'Gurv-aṣṭaka', reference:'Gurv-aṣṭaka 6', group:'gurvastakam', text:`nikuñja-yūno rati-keli-siddhyai\nyā yālibhir yuktir apekṣaṇīyā\ntatrāti-dākṣyād ati-vallabhasya\nvande guroḥ śrī-caraṇāravindam`, translation:'The guru is very expert in assisting the gopīs in arranging the loving affairs of Rādhā-Kṛṣṇa. I worship his lotus feet.' },
  { id:'ga-8', meter:'mantra', difficulty:'medium', source:'Gurv-aṣṭaka', reference:'Gurv-aṣṭaka 8', group:'gurvastakam', text:`yasya prasādād bhagavat-prasādo\nyasyāprasādān na gatiḥ kuto 'pi\ndhyāyan stuvaṁs tasya yaśas tri-sandhyaṁ\nvande guroḥ śrī-caraṇāravindam`, translation:'By the guru\'s mercy one receives Kṛṣṇa\'s mercy. Without his grace, there is no means of advancement. I worship his lotus feet.' },

  // ══════ MAṄGALA ĀRATĪ — Udilo Aruṇa ══════

  { id:'ma-1', meter:'mantra', difficulty:'medium', source:'Maṅgala Āratī', reference:'Udilo Aruṇa (1)', group:'udilo-aruna', text:`udilo aruṇa pūraba-bhāge\ndvija-maṇi gorā amani jāge\nbhakata-samūha loiyā sāthe\ngelā nagara-brāje`, translation:'When the eastern horizon glowed, the jewel of the twice-born, Lord Gaurāṅga, awoke and took His devotees to the streets of the city.' },
  { id:'ma-2', meter:'mantra', difficulty:'easy-medium', source:'Maṅgala Āratī', reference:'Udilo Aruṇa (2)', group:'udilo-aruna', text:`tāthai tāthai bājalo khol\nghana ghana tāhe jhā̃jera rol\npreme ḍhala ḍhala soṇāra aṅga\ncaraṇe nūpura bāje`, translation:'The mṛdaṅgas sounded tāthai tāthai and the cymbals played rhythmically. His golden body swayed in ecstasy, and ankle bells jingled on His feet.' },
  { id:'ma-3', meter:'mantra', difficulty:'medium', source:'Maṅgala Āratī', reference:'Udilo Aruṇa (3)', group:'udilo-aruna', text:`mukunda mādhava yādava hari\nbolore bolore vadana bhari'\nmiśra śrīvāsa ādi bhakta-bṛnda\nlaoyāi bole hari hari`, translation:'Fill your mouths and chant — Mukunda! Mādhava! Yādava! Hari! Led by Miśra, Śrīvāsa, and other devotees calling Hari Hari!' },

  // ══════ ADDITIONAL GAURA ĀRATĪ VERSES ══════

  { id:'ar-1', meter:'mantra', difficulty:'medium', source:'Gaura Āratī', reference:'Gaura Āratī (2)', group:'gaura-arati', text:`dakṣiṇe nitāicā̃da bāme gadādhara\nnikate advaita śrīnivāsa chatra-dhara\nbosiyāche gorācā̃da ratna-siṁhāsane\nārati koroye brahmā-ādi deva-gaṇe`, translation:'To the right is Nityānanda, to the left Gadādhara, nearby Advaita and Śrīnivāsa holding an umbrella. Gorācānda sits on a jeweled throne while Brahmā and the devas perform His āratī.' },
  { id:'ar-2', meter:'mantra', difficulty:'medium', source:'Gaura Āratī', reference:'Gaura Āratī (3)', group:'gaura-arati', text:`nayanera koṇe gorā jāhāra parasa\nsei se paraśa-mani jāhāra sparśe hoy āśa\ngorā-sundara dekhiyā lukāya caraṇe\ngorā-aṅge jhalake hīrā mandire`, translation:'He whose glance from the corner of His eyes, that touchstone, awakens desire in all. Seeing beautiful Gorā, everyone takes shelter of His feet.' },

  // ══════ NṚSIṀHA PRAYERS (sung after every āratī) ══════

  { id:'nr-1', meter:'mantra', difficulty:'easy-medium', source:'Nṛsiṁha Prayers', reference:'Nṛsiṁha Praṇāma (full)', group:'nrsimha-prayers', text:`namas te narasiṁhāya\nprahlādāhlāda-dāyine\nhiraṇyakaśipor vakṣaḥ-\nśilā-ṭaṅka-nakhālaye`, translation:'Obeisances to Lord Narasiṁha who gives joy to Prahlāda and whose nails are like chisels on the stonelike chest of Hiraṇyakaśipu.' },
  { id:'nr-2', meter:'mantra', difficulty:'medium', source:'Nṛsiṁha Prayers', reference:'Nṛsiṁha Prayer 2', group:'nrsimha-prayers', text:`ito nṛsiṁhaḥ parato nṛsiṁho\nyato yato yāmi tato nṛsiṁhaḥ\nbahir nṛsiṁho hṛdaye nṛsiṁho\nnṛsiṁham ādiṁ śaraṇaṁ prapadye`, translation:'Lord Nṛsiṁha is here and there. Wherever I go He is there. He is in the heart, He is outside. I surrender to that primeval Lord Nṛsiṁha.' },
  { id:'nr-3', meter:'mantra', difficulty:'medium', source:'Nṛsiṁha Prayers', reference:'Nṛsiṁha Prayer 3', group:'nrsimha-prayers', text:`tava kara-kamala-vare nakham adbhuta-śṛṅgaṁ\ndalita-hiraṇyakaśipu-tanu-bhṛṅgam\nkeśava dhṛta-narahari-rūpa jaya jagadīśa hare`, translation:'O Keśava! Your wondrous lion-man claws tore apart the wasp-like body of Hiraṇyakaśipu. O Lord of the universe, all glories to You!' },

  // ══════ TULASĪ PRAYERS ══════

  { id:'tul-1', meter:'mantra', difficulty:'easy-medium', source:'Tulasī Prayers', reference:'Tulasī Kṛṣṇa-preyasī', group:'tulasi-prayers', text:`namo namaḥ tulasī kṛṣṇa-preyasi namo namaḥ\nrādhā-kṛṣṇa-sevā pābo ei abhilāṣī`, translation:'I repeatedly offer obeisances to Tulasī, who is dear to Kṛṣṇa. My desire is to attain the service of Rādhā-Kṛṣṇa.' },
  { id:'tul-2', meter:'mantra', difficulty:'easy-medium', source:'Tulasī Prayers', reference:'Tulasī Pradakṣiṇa', group:'tulasi-prayers', text:`yāni kāni ca pāpāni\nbrahma-hatyādikāni ca\ntāni tāni praṇaśyanti\npradakṣiṇaḥ pade pade`, translation:'By circumambulating Tulasī-devī, all sins including brahma-hatyā are destroyed at every step.' },

  // ══════ GURU PŪJĀ — Śrī-guru-caraṇa-padma ══════

  { id:'gp-1', meter:'mantra', difficulty:'easy', source:'Guru Pūjā', reference:'Śrī Guru-caraṇa-padma (1)', group:'guru-puja', text:`śrī-guru-caraṇa-padma kevala-bhakati-sadma\nbando muñi sāvadhāna mate\njā̃hāra prasāde bhāi e bhava toriyā jāi\nkṛṣṇa-prāpti hoy jā̃hā ha'te`, translation:'The lotus feet of the guru are the abode of pure devotion. I bow to them with care. By his mercy we cross the ocean of birth and death and attain Kṛṣṇa.' },
  { id:'gp-2', meter:'mantra', difficulty:'easy-medium', source:'Guru Pūjā', reference:'Śrī Guru-caraṇa-padma (2)', group:'guru-puja', text:`guru-mukha-padma-vākya cittete koriyā aikya\nār nā koriho mane āśā\nśrī-guru-caraṇe rati ei se uttama-gati\nje prasāde pūre sarva āśā`, translation:'Make the words from the guru\'s lotus mouth one with your heart, and do not desire anything else. Attachment to the guru\'s lotus feet is the supreme goal; by his mercy all desires are fulfilled.' },

  // ══════ DĀMODARĀṢṬAKA (missing verses) ══════

  { id:'da-2', meter:'mantra', difficulty:'medium-hard', source:'Dāmodarāṣṭaka', reference:'Dāmodarāṣṭaka 2', group:'damodarastaka', text:`rudantaṁ muhur netra-yugmaṁ mṛjantam\nlalāṭa-phalake viśadaṁ sva-dantam\nithambhūta-lakṣmī-tanūn-nāṅkitaṁ tad-\ndāmodara-saṁsāra-sindhum-upetam`, translation:'He cries repeatedly, rubbing both eyes with His hands. His teeth shine against His forehead. This Dāmodara — I approach Him.' },
  { id:'da-3', meter:'mantra', difficulty:'medium-hard', source:'Dāmodarāṣṭaka', reference:'Dāmodarāṣṭaka 3', group:'damodarastaka', text:`itīdṛk sva-līlābhir ānanda-kuṇḍe\nsva-ghoṣaṁ nimajjantam ākhyāpayantam\ntadīyeśita-jñeṣu bhaktair jitatvaṁ\npunaḥ prematas taṁ śatāvṛtti vande`, translation:'By such pastimes He floods the residents of Gokula with bliss. He shows that He is conquered by His pure devotees. Again and again with love I worship Him.' },

  // ══════ SANDHYĀ ĀRATĪ SONGS ══════

  { id:'sa-1', meter:'mantra', difficulty:'medium', source:'Sandhyā Āratī', reference:'Bhoga Āratī (1)', group:'bhoga-arati', text:`bhaja bhakata-vatsala śrī-gaurahari\nśrī-gaurahari sohi goṣṭha-bihārī\nnanda-yaśomatī-citta-hārī`, translation:'Worship the Lord who is dear to the devotees, Śrī Gaurahari, who enjoys pastimes in the cow-pastures and steals the hearts of Nanda and Yaśodā.' },

  // ══════ ŚAYANA ĀRATĪ SONGS ══════

  { id:'sy-1', meter:'mantra', difficulty:'easy-medium', source:'Śayana Āratī', reference:'Jaya Jaya Gopāla', text:`jaya jaya gopāla hare jaya jaya gopāla\njaya jaya gopāla hare jaya jaya gopāla`, translation:'All glories to Gopāla! All glories to Hari!' },
  { id:'sy-2', meter:'mantra', difficulty:'medium', source:'Śayana Āratī', reference:'Jaya Rādhā-Mādhava (Śayana)', text:`jaya rādhā-mādhava kuñja-bihārī\ngopī-jana-vallabha giri-vara-dhārī\nyaśodā-nandana braja-jana-raṇjana\nyamunā-tīra-vana-cārī`, translation:'All glories to Rādhā-Mādhava, the enjoyer of the groves, the lifter of Govardhana, son of Yaśodā, who wanders along the banks of the Yamunā.' },

  // ══════ BHĀGAVATAM CLASS OPENING PRAYERS ══════

  { id:'bc-1', meter:'mantra', difficulty:'easy', source:'Bhāgavatam Class', reference:'Oṁ Namo Bhagavate', text:`oṁ namo bhagavate vāsudevāya\noṁ namo bhagavate vāsudevāya\noṁ namo bhagavate vāsudevāya`, translation:'I offer my obeisances unto the Supreme Lord Vāsudeva. (Chanted three times before class.)' },
  { id:'bc-2', meter:'mantra', difficulty:'medium', source:'Bhāgavatam Class', reference:'SB 1.2.11 (Vadanti)', text:`vadanti tat tattva-vidas\ntattvaṁ yaj jñānam advayam\nbrahmeti paramātmeti\nbhagavān iti śabdyate`, translation:'Learned transcendentalists who know the Absolute Truth call this nondual substance Brahman, Paramātmā or Bhagavān.' },
  { id:'bc-3', meter:'mantra', difficulty:'medium', source:'Bhāgavatam Class', reference:'SB 1.1.1 (Janmādy)', text:`janmādy asya yato 'nvayād itarataś\ncārtheṣv abhijñaḥ svarāṭ\ntene brahma hṛdā ya ādi-kavaye\nmuhyanti yat sūrayaḥ`, translation:'I meditate upon Lord Śrī Kṛṣṇa, the Absolute Truth, the source of creation, from whom even Brahmā received Vedic knowledge.' },

  // ══════ UPADEŚĀMṚTA (Rūpa Gosvāmī) ══════

  { id:'ua-1', meter:'anushtubh', difficulty:'medium', source:'Upadeśāmṛta', reference:'Upadeśāmṛta 1', text:`vāco vegaṁ manasaḥ krodha-vegaṁ\njihvā-vegam udaropastha-vegam\netān vegān yo viṣaheta dhīraḥ\nsarvām apīmāṁ pṛthivīṁ sa śiṣyāt`, translation:'A wise person who can tolerate the urges of speech, mind, anger, tongue, belly and genitals can make disciples all over the world.' },
  { id:'ua-2', meter:'anushtubh', difficulty:'medium', source:'Upadeśāmṛta', reference:'Upadeśāmṛta 2', text:`atyāhāraḥ prayāsaś ca\nprajalpo niyamāgrahaḥ\njana-saṅgaś ca laulyaṁ ca\nṣaḍbhir bhaktir vinaśyati`, translation:'Devotion is destroyed by overeating, over-endeavoring, idle talk, neglecting rules, bad association, and greed.' },
  { id:'ua-3', meter:'anushtubh', difficulty:'medium', source:'Upadeśāmṛta', reference:'Upadeśāmṛta 3', text:`utsāhān niścayād dhairyāt\ntat-tat-karma-pravartanāt\nsaṅga-tyāgāt sato vṛtteḥ\nṣaḍbhir bhaktiḥ prasidhyati`, translation:'Devotion is advanced by enthusiasm, confidence, patience, proper activities, good association, and following the saintly path.' },
  { id:'ua-5', meter:'anushtubh', difficulty:'medium-hard', source:'Upadeśāmṛta', reference:'Upadeśāmṛta 5', text:`kṛṣṇeti yasya giri taṁ manasādriyeta\ndīkṣāsti cet praṇatibhiś ca bhajantam īśam\nśuśrūṣayā bhajana-vijñam ananyam anya-\nnindādi-śūnya-hṛdam īpsita-saṅga-labdhyā`, translation:'One should mentally honor those who chant Kṛṣṇa\'s name, bow before initiates, and serve pure devotees whose hearts are free from fault-finding.' },
  { id:'ua-6', meter:'anushtubh', difficulty:'medium-hard', source:'Upadeśāmṛta', reference:'Upadeśāmṛta 6', text:`dṛṣṭaiḥ svabhāva-janitair vapuṣaś ca doṣair\nna prākṛtatvam iha bhakta-janasya paśyet\ngaṅgāmbhasāṁ na khalu budbuda-phena-paṅkair\nbrahma-dravatvam apagacchati nīra-dharmaiḥ`, translation:'Do not see a devotee from a material point of view, just as the Gaṅgā does not lose its spiritual nature due to bubbles and foam.' },
  { id:'ua-8', meter:'anushtubh', difficulty:'hard', source:'Upadeśāmṛta', reference:'Upadeśāmṛta 8', text:`smṛtyoḥ krameṇa rasanā-manasī niyojya\ntiṣṭhan vraje tad-anurāgi janānugāmī\nkālaṁ nayed akhilam ity upadeśa-sāram`, translation:'Gradually engage the tongue and mind in remembrance. Reside in Vraja, following those who are attached to the Lord. This is the essence of all instruction.' },
  { id:'ua-9', meter:'anushtubh', difficulty:'hard', source:'Upadeśāmṛta', reference:'Upadeśāmṛta 9', text:`vaikuṇṭhāj janito varā madhu-purī tatrāpi rāsotsavād\nvṛndāraṇyam udāra-pāṇi-ramaṇāt tatrāpi govardhanaḥ\nrādhā-kuṇḍam ihāpi gokula-pateḥ premāmṛtāplāvanāt\nkuryād asya virājato giri-taṭe sevāṁ vivekī na kaḥ`, translation:'Superior to Vaikuṇṭha is Mathurā, better still is Vṛndāvana, yet more so Govardhana, and best of all is Rādhā-kuṇḍa. What intelligent person will not serve there?' },

  // ══════ BHAKTI-RASĀMṚTA-SINDHU (Rūpa Gosvāmī) ══════

  { id:'brs-1.1.11', meter:'anushtubh', difficulty:'medium-hard', source:'Bhakti-rasāmṛta-sindhu', reference:'BRS 1.1.11', text:`anyābhilāṣitā-śūnyaṁ\njñāna-karmādy-anāvṛtam\nānukūlyena kṛṣṇānu-\nśīlanaṁ bhaktir uttamā`, translation:'The highest devotion is that which is favorable to Kṛṣṇa, free from selfish desires, and uncovered by jñāna or karma.' },
  { id:'brs-1.1.12', meter:'anushtubh', difficulty:'hard', source:'Bhakti-rasāmṛta-sindhu', reference:'BRS 1.1.12', text:`sarvopādhi-vinirmuktaṁ\ntat-paratvena nirmalam\nhṛṣīkeṇa hṛṣīkeśa-\nsevanaṁ bhaktir ucyate`, translation:'Bhakti is the engagement of all senses in the service of the master of the senses, free from all designations, purified by transcendence.' },
  { id:'brs-1.2.187', meter:'anushtubh', difficulty:'medium', source:'Bhakti-rasāmṛta-sindhu', reference:'BRS 1.2.187', text:`iha yasya harer dāsye\nkarmaṇā manasā girā\nnikhilāsv apy avasthāsu\njīvan-muktaḥ sa ucyate`, translation:'One who engages body, mind and words in the service of Hari in all circumstances is considered liberated even while living.' },
  { id:'brs-1.2.234', meter:'anushtubh', difficulty:'medium-hard', source:'Bhakti-rasāmṛta-sindhu', reference:'BRS 1.2.234', text:`ataḥ śrī-kṛṣṇa-nāmādi\nna bhaved grāhyam indriyaiḥ\nsevonmukhe hi jihvādau\nsvayam eva sphuraty adaḥ`, translation:'The name of Kṛṣṇa cannot be grasped by material senses. It manifests on the tongue when one has the attitude of service.' },

  // ══════ VEDĀNTA-SŪTRA ══════

  { id:'vs-1.1.1', meter:'longer', difficulty:'medium', source:'Vedānta-sūtra', reference:'VS 1.1.1', text:`athāto brahma-jijñāsā`, translation:'Now, therefore, let us inquire about Brahman — the Absolute Truth.' },
  { id:'vs-1.1.2', meter:'longer', difficulty:'medium', source:'Vedānta-sūtra', reference:'VS 1.1.2', text:`janmādy asya yataḥ`, translation:'Brahman is that from which everything originates.' },
  { id:'vs-1.1.3', meter:'longer', difficulty:'hard', source:'Vedānta-sūtra', reference:'VS 1.1.3', text:`śāstra-yonitvāt`, translation:'Brahman is known through the scriptures.' },

  // ══════ NĀRADA BHAKTI SŪTRA ══════

  { id:'nbs-2', meter:'longer', difficulty:'easy-medium', source:'Nārada Bhakti Sūtra', reference:'NBS 2', text:`sā tv asmin parama-prema-rūpā`, translation:'That devotion is of the nature of supreme love for Him.' },
  { id:'nbs-3', meter:'longer', difficulty:'easy-medium', source:'Nārada Bhakti Sūtra', reference:'NBS 3', text:`amṛta-svarūpā ca`, translation:'And it is immortal in nature.' },
  { id:'nbs-5', meter:'longer', difficulty:'easy', source:'Nārada Bhakti Sūtra', reference:'NBS 5', text:`yat prāpya na kiñcid vāñchati na śocati na dveṣṭi na ramate notsāhī bhavati`, translation:'Having obtained it, one desires nothing, grieves for nothing, hates nothing, delights in nothing else, and makes no selfish endeavor.' },
  { id:'nbs-36', meter:'longer', difficulty:'medium', source:'Nārada Bhakti Sūtra', reference:'NBS 36', text:`tad eva sādhana-gaṇānāṁ kāraṇaṁ matiḥ`, translation:'The means of achieving devotion is devotion itself, according to wise opinion.' },
  { id:'nbs-68', meter:'longer', difficulty:'medium', source:'Nārada Bhakti Sūtra', reference:'NBS 68', text:`sat-saṅgo labhyate sarvathā\ndurlabho 'gamyo 'moghaś ca\nlabhyate tat-kṛpayaiva`, translation:'The association of saints is obtained only by the Lord\'s mercy. It is difficult to attain, unfathomable, and never fails.' },

  // ══════ ĪŚOPANIṢAD (additional) ══════

  { id:'iso-2', meter:'anushtubh', difficulty:'medium', source:'Īśopaniṣad', reference:'Īśo 2', text:`kurvann eveha karmāṇi\njijīviṣec chataṁ samāḥ\nevaṁ tvayi nānyatheto 'sti\nna karma lipyate nare`, translation:'One may aspire to live for hundreds of years if he works in accordance with the Lord. Thus karma does not bind.' },
  { id:'iso-12', meter:'anushtubh', difficulty:'medium-hard', source:'Īśopaniṣad', reference:'Īśo 12', text:`andhaṁ tamaḥ praviśanti\nye 'sambhūtim upāsate\ntato bhūya iva te tamo\nya u sambhūtyām ratāḥ`, translation:'Those who worship the demigods enter blinding darkness, and those who worship the impersonal Absolute enter even greater darkness.' },
  { id:'iso-15', meter:'anushtubh', difficulty:'hard', source:'Īśopaniṣad', reference:'Īśo 15', text:`hiraṇmayena pātreṇa\nsatyasyāpihitaṁ mukham\ntat tvaṁ pūṣann apāvṛṇu\nsatya-dharmāya dṛṣṭaye`, translation:'O my Lord, sustainer, the face of truth is covered by Your golden effulgence. Remove it so I may see You.' },
  { id:'iso-18', meter:'anushtubh', difficulty:'hard', source:'Īśopaniṣad', reference:'Īśo 18', text:`agne naya supathā rāye asmān\nviśvāni deva vayunāni vidvān\nyuyodhy asmaj juhurāṇam eno\nbhūyiṣṭhāṁ te nama-uktiṁ vidhema`, translation:'O Lord, lead us on the right path. You know all our deeds. Free us from sinful reactions. We offer our obeisances again and again.' },

  // ══════ CAITANYA-CARITĀMṚTA (additional) ══════

  { id:'cc-mad-6.254', meter:'anushtubh', difficulty:'medium-hard', source:'Caitanya-caritāmṛta', reference:'CC Madhya 6.254', text:`nāhaṁ vipro na ca nara-patir nāpi vaiśyo na śūdro\nnāhaṁ varṇī na ca gṛha-patir no vanastho yatir vā\nkintu prodyan-nikhila-paramānanda-pūrnāmṛtābdher\ngopī-bhartuḥ pada-kamalayor dāsa-dāsānudāsaḥ`, translation:'I am not a brāhmaṇa, kṣatriya, vaiśya, or śūdra. I am the servant of the servant of the servant of the gopīs\' beloved.' },
  { id:'cc-mad-19.151', meter:'anushtubh', difficulty:'medium', source:'Caitanya-caritāmṛta', reference:'CC Madhya 19.151', text:`brahmāṇḍa bhramite kona bhāgyavān jīva\nguru-kṛṣṇa-prasāde pāya bhakti-latā-bīja`, translation:'Wandering throughout the universe, some fortunate soul receives the seed of the bhakti creeper by the mercy of guru and Kṛṣṇa.' },
  { id:'cc-adi-1.14', meter:'anushtubh', difficulty:'easy-medium', source:'Caitanya-caritāmṛta', reference:'CC Ādi 1.14', text:`vande śrī-kṛṣṇa-caitanya-\nnityānandau sahoditau\ngauḍodaye puṣpavantau\ncitrau śan-dau tamo-nudau`, translation:'I worship Śrī Kṛṣṇa Caitanya and Nityānanda, who rose simultaneously like the sun and moon to dispel the darkness of ignorance.' },
  { id:'cc-adi-17.31', meter:'anushtubh', difficulty:'medium', source:'Caitanya-caritāmṛta', reference:'CC Ādi 17.31', text:`tṛṇād api sunīcena\ntaror api sahiṣṇunā\namāninā mānadena\nkīrtanīyaḥ sadā hariḥ`, translation:'One who is humbler than grass, more tolerant than a tree, offering respect to others without expecting any — can constantly chant the holy name.' },
  { id:'cc-mad-22.107', meter:'anushtubh', difficulty:'medium-hard', source:'Caitanya-caritāmṛta', reference:'CC Madhya 22.107', text:`nityānanda-svarūpaṁ śrī-\nadvaita-prakāśaṁ ca yo 'vatāra-viśeṣān\njānāti tattvatah so 'yaṁ\nmukto bhavati saṁsṛteḥ`, translation:'One who understands the truth about the Lord\'s incarnations and expansions becomes liberated from material existence.' },

  // ══════ ŚRĪMAD-BHĀGAVATAM (advanced — higher cantos) ══════

  { id:'sb-1.1.2', meter:'longer', difficulty:'hard', source:'Śrīmad-Bhāgavatam', reference:'ŚB 1.1.2', text:`dharmaḥ projjhita-kaitavo 'tra paramo nirmatsarāṇāṁ satāṁ\nvedyaṁ vāstavam atra vastu śivadaṁ tāpa-trayonmūlanam\nśrīmad-bhāgavate mahā-muni-kṛte kiṁ vā parair īśvaraḥ\nsadyo hṛdy avarudhyate 'tra kṛtibhiḥ śuśrūṣubhis tat-kṣaṇāt`, translation:'In Śrīmad-Bhāgavatam, completely rejecting all cheating religion, the highest truth is presented for the non-envious.' },
  { id:'sb-3.29.11-12', meter:'anushtubh', difficulty:'medium', source:'Śrīmad-Bhāgavatam', reference:'ŚB 3.29.11-12', text:`mad-guṇa-śruti-mātreṇa\nmayi sarva-guhāśaye\nmano-gatir avicchinnā\nyathā gaṅgāmbhaso 'mbudhau`, translation:'Upon hearing My transcendental qualities, an uninterrupted flow of devotion enters the heart, like the Gaṅgā flowing to the ocean.' },
  { id:'sb-4.31.14', meter:'anushtubh', difficulty:'medium-hard', source:'Śrīmad-Bhāgavatam', reference:'ŚB 4.31.14', text:`yathā taror mūla-niṣecanena\ntṛpyanti tat-skandha-bhujopaśākhāḥ\nprāṇopahārāc ca yathendriyāṇāṁ\ntathaiva sarvārhaṇam acyutejyā`, translation:'As watering the root of a tree nourishes all parts, and as food enlivens all senses, worshiping Acyuta satisfies everyone.' },
  { id:'sb-5.5.1', meter:'longer', difficulty:'hard', source:'Śrīmad-Bhāgavatam', reference:'ŚB 5.5.1', text:`nāyaṁ deho deha-bhājāṁ nṛ-loke\nkaṣṭān kāmān arhate viḍ-bhujāṁ ye\ntapo divyaṁ putrakā yena sattvaṁ\nśuddhyed yasmād brahma-saukhyaṁ tv anantam`, translation:'The human body is not meant for sense gratification like hogs. One should undergo austerities for purification, which leads to unlimited spiritual bliss.' },
  { id:'sb-5.18.12', meter:'anushtubh', difficulty:'medium', source:'Śrīmad-Bhāgavatam', reference:'ŚB 5.18.12', text:`yasyāsti bhaktir bhagavaty akiñcanā\nsarvair guṇais tatra samāsate surāḥ\nharāv abhaktasya kuto mahad-guṇā\nmano-rathenāsati dhāvato bahiḥ`, translation:'All demigods and their qualities reside in one who has unflinching devotion. But where are good qualities in a non-devotee whose mind runs after the external?' },
  { id:'sb-6.1.13-14', meter:'anushtubh', difficulty:'hard', source:'Śrīmad-Bhāgavatam', reference:'ŚB 6.1.13-14', text:`tapasā brahmacaryeṇa\nśamena ca damena ca\ntyāgena satya-śaucābhyāṁ\nyamena niyamena vā\ndeha-vāg-buddhijaṁ dhīrā\ndharmajñāḥ śraddhayānvitāḥ\nkṣipanty aghaṁ mahad api\nveṇu-gulmam ivānalaḥ`, translation:'Through austerity, celibacy, self-control, charity, truthfulness, and cleanliness, wise men burn even the greatest sins like fire burns bamboo.' },
  { id:'sb-11.14.23', meter:'anushtubh', difficulty:'medium-hard', source:'Śrīmad-Bhāgavatam', reference:'ŚB 11.14.23', text:`bhaktyāham ekayā grāhyaḥ\nśraddhayātmā priyaḥ satām\nbhaktiḥ punāti man-niṣṭhā\nśva-pākān api sambhavāt`, translation:'I can be attained only by devotion with faith. I am dear to the saintly. Devotion fixed on Me purifies even the dog-eaters from birth.' },

  // ══════ PREMA-VIVARTA (Jagadānanda Paṇḍita) ══════

  { id:'pv-7.3', meter:'mantra', difficulty:'medium', source:'Prema-vivarta', reference:'PV 7.3', text:`gaura āmāra ye saba sthāne\nkoralo bhramaṇa raṅge\nse-saba sthāna heribo āmi\npraṇayi-bhakata-saṅge`, translation:'All the places where Lord Gaura wandered in ecstasy — I will visit them in the company of loving devotees.' },

  // ══════ ADDITIONAL BHAGAVAD-GĪTĀ (philosophical depth) ══════

  { id:'bg-2.12', meter:'anushtubh', difficulty:'medium', source:'Bhagavad-gītā', reference:'BG 2.12', text:`na tv evāhaṁ jātu nāsaṁ\nna tvaṁ neme janādhipāḥ\nna caiva na bhaviṣyāmaḥ\nsarve vayam ataḥ param`, translation:'Never was there a time when I did not exist, nor you, nor any of these kings; and in the future none of us shall cease to exist.' },
  { id:'bg-2.13', meter:'anushtubh', difficulty:'medium', source:'Bhagavad-gītā', reference:'BG 2.13', text:`dehino 'smin yathā dehe\nkaumāraṁ yauvanaṁ jarā\ntathā dehāntara-prāptir\ndhīras tatra na muhyati`, translation:'As the embodied soul continuously passes from childhood to youth to old age, similarly it passes into another body at death.' },
  { id:'bg-2.14', meter:'anushtubh', difficulty:'medium', source:'Bhagavad-gītā', reference:'BG 2.14', text:`mātrā-sparśās tu kaunteya\nśītoṣṇa-sukha-duḥkha-dāḥ\nāgamāpāyino 'nityās\ntāṁs titikṣasva bhārata`, translation:'The appearance and disappearance of happiness and distress are like winter and summer seasons. One must learn to tolerate them.' },
  { id:'bg-3.27', meter:'anushtubh', difficulty:'medium-hard', source:'Bhagavad-gītā', reference:'BG 3.27', text:`prakṛteḥ kriyamāṇāni\nguṇaiḥ karmāṇi sarvaśaḥ\nahaṅkāra-vimūḍhātmā\nkartāham iti manyate`, translation:'All activities are carried out by the modes of material nature. The soul bewildered by false ego thinks, "I am the doer."' },
  { id:'bg-7.14', meter:'anushtubh', difficulty:'medium-hard', source:'Bhagavad-gītā', reference:'BG 7.14', text:`daivī hy eṣā guṇa-mayī\nmama māyā duratyayā\nmām eva ye prapadyante\nmāyām etāṁ taranti te`, translation:'This divine energy of Mine consisting of the three modes is difficult to overcome. But those who surrender unto Me cross beyond it easily.' },
  { id:'bg-9.10', meter:'anushtubh', difficulty:'medium', source:'Bhagavad-gītā', reference:'BG 9.10', text:`mayādhyakṣeṇa prakṛtiḥ\nsūyate sa-carācaram\nhetunānena kaunteya\njagad viparivartate`, translation:'Under My supervision, material nature produces all moving and nonmoving beings. By this cause the universe revolves.' },
  { id:'bg-14.26', meter:'anushtubh', difficulty:'medium', source:'Bhagavad-gītā', reference:'BG 14.26', text:`māṁ ca yo 'vyabhicāreṇa\nbhakti-yogena sevate\nsa guṇān samatītyaitān\nbrahma-bhūyāya kalpate`, translation:'One who engages in full devotional service, unfailing in all circumstances, transcends the modes and reaches the Brahman platform.' },
  { id:'bg-18.55', meter:'anushtubh', difficulty:'medium-hard', source:'Bhagavad-gītā', reference:'BG 18.55', text:`bhaktyā mām abhijānāti\nyāvān yaś cāsmi tattvataḥ\ntato māṁ tattvato jñātvā\nviśate tad-anantaram`, translation:'One can understand Me as I am only by devotional service. And when in full consciousness of Me, one can enter My kingdom.' },
]

// Helper functions
export function getSlokasByMeter(meter: Meter): SlokaEntry[] { return slokaLibrary.filter(s => s.meter === meter) }
export function getSlokasByDifficulty(difficulty: Difficulty): SlokaEntry[] { return slokaLibrary.filter(s => s.difficulty === difficulty) }
export function getSlokasByMeterAndDifficulty(meter: Meter, difficulty: Difficulty): SlokaEntry[] { return slokaLibrary.filter(s => s.meter === meter && s.difficulty === difficulty) }

export const difficultyLabels: Record<Difficulty, string> = { 'easy':'Easy', 'easy-medium':'Easy-Medium', 'medium':'Medium', 'medium-hard':'Medium-Hard', 'hard':'Hard' }
export const difficultyColors: Record<Difficulty, string> = { 'easy':'bg-green-100 text-green-700 border-green-300', 'easy-medium':'bg-lime-100 text-lime-700 border-lime-300', 'medium':'bg-yellow-100 text-yellow-700 border-yellow-300', 'medium-hard':'bg-orange-100 text-orange-700 border-orange-300', 'hard':'bg-red-100 text-red-700 border-red-300' }
