export type Difficulty = 'easy' | 'easy-medium' | 'medium' | 'medium-hard' | 'hard'
export type Meter = 'anushtubh' | 'trishtubh' | 'jagati' | 'vasanta_tilaka' | 'longer' | 'mantra'

export interface SlokaEntry {
  id: string
  text: string
  reference: string
  source: string
  translation: string
  meter: Meter
  difficulty: Difficulty
}

// Difficulty = PRONUNCIATION complexity (dynamic user scoring overlays this)
export const slokaLibrary: SlokaEntry[] = [

  // ══════ BHAGAVAD-GĪTĀ (anuṣṭubh) ══════

  // Easy
  { id:'bg-10.8', meter:'anushtubh', difficulty:'easy', source:'Bhagavad-gītā', reference:'BG 10.8', text:`ahaṁ sarvasya prabhavo\nmattaḥ sarvaṁ pravartate\niti matvā bhajante māṁ\nbudhā bhāva-samanvitāḥ`, translation:'I am the source of all. Everything emanates from Me. The wise worship Me with devotion.' },
  { id:'bg-9.26', meter:'anushtubh', difficulty:'easy', source:'Bhagavad-gītā', reference:'BG 9.26', text:`patraṁ puṣpaṁ phalaṁ toyaṁ\nyo me bhaktyā prayacchati\ntad ahaṁ bhakty-upahṛtam\naśnāmi prayatātmanaḥ`, translation:'A leaf, flower, fruit, water — if offered with devotion, I accept it.' },
  { id:'bg-9.34', meter:'anushtubh', difficulty:'easy', source:'Bhagavad-gītā', reference:'BG 9.34', text:`man-manā bhava mad-bhakto\nmad-yājī māṁ namaskuru\nmām evaiṣyasi yuktvaivam\nātmānaṁ mat-parāyaṇaḥ`, translation:'Always think of Me, become My devotee, worship Me and offer obeisances.' },
  { id:'bg-7.7', meter:'anushtubh', difficulty:'easy', source:'Bhagavad-gītā', reference:'BG 7.7', text:`mattaḥ parataraṁ nānyat\nkiñcid asti dhanañjaya\nmayi sarvam idaṁ protaṁ\nsūtre maṇi-gaṇā iva`, translation:'There is no truth superior to Me. Everything rests upon Me, as pearls on a thread.' },
  { id:'bg-7.19', meter:'anushtubh', difficulty:'easy', source:'Bhagavad-gītā', reference:'BG 7.19', text:`bahūnāṁ janmanām ante\njñānavān māṁ prapadyate\nvāsudevaḥ sarvam iti\nsa mahātmā su-durlabhaḥ`, translation:'After many births, the wise surrender unto Me. Such a great soul is very rare.' },
  { id:'bg-12.8', meter:'anushtubh', difficulty:'easy', source:'Bhagavad-gītā', reference:'BG 12.8', text:`mayy eva mana ādhatsva\nmayi buddhiṁ niveśaya\nnivasiṣyasi mayy eva\nata ūrdhvaṁ na saṁśayaḥ`, translation:'Fix your mind and intelligence upon Me. You will live in Me always, without doubt.' },
  { id:'bg-4.11', meter:'anushtubh', difficulty:'easy', source:'Bhagavad-gītā', reference:'BG 4.11', text:`ye yathā māṁ prapadyante\ntāṁs tathaiva bhajāmy aham\nmama vartmānuvartante\nmanuṣyāḥ pārtha sarvaśaḥ`, translation:'As they surrender unto Me, I reward them accordingly.' },

  // Easy-Medium
  { id:'bg-4.8', meter:'anushtubh', difficulty:'easy-medium', source:'Bhagavad-gītā', reference:'BG 4.8', text:`paritrāṇāya sādhūnāṁ\nvināśāya ca duṣkṛtām\ndharma-saṁsthāpanārthāya\nsambhavāmi yuge yuge`, translation:'To protect the pious and annihilate the wicked, I appear millennium after millennium.' },
  { id:'bg-18.66', meter:'anushtubh', difficulty:'easy-medium', source:'Bhagavad-gītā', reference:'BG 18.66', text:`sarva-dharmān parityajya\nmām ekaṁ śaraṇaṁ vraja\nahaṁ tvāṁ sarva-pāpebhyo\nmokṣayiṣyāmi mā śucaḥ`, translation:'Abandon all dharmas and surrender unto Me. I shall deliver you from all sins.' },
  { id:'bg-9.22', meter:'anushtubh', difficulty:'easy-medium', source:'Bhagavad-gītā', reference:'BG 9.22', text:`ananyāś cintayanto māṁ\nye janāḥ paryupāsate\nteṣāṁ nityābhiyuktānāṁ\nyoga-kṣemaṁ vahāmy aham`, translation:'For those who worship Me with exclusive devotion, I carry what they lack and preserve what they have.' },
  { id:'bg-8.7', meter:'anushtubh', difficulty:'easy-medium', source:'Bhagavad-gītā', reference:'BG 8.7', text:`tasmāt sarveṣu kāleṣu\nmām anusmara yudhya ca\nmayy arpita-mano-buddhir\nmām evaiṣyasy asaṁśayaḥ`, translation:'Always remember Me and fight. With mind and intelligence fixed on Me, you will come to Me.' },
  { id:'bg-15.15', meter:'anushtubh', difficulty:'easy-medium', source:'Bhagavad-gītā', reference:'BG 15.15', text:`sarvasya cāhaṁ hṛdi sanniviṣṭo\nmattaḥ smṛtir jñānam apohanaṁ ca\nvedaiś ca sarvair aham eva vedyo\nvedānta-kṛd veda-vid eva cāham`, translation:'I am seated in everyone\'s heart. From Me come remembrance, knowledge and forgetfulness.' },
  { id:'bg-6.47', meter:'anushtubh', difficulty:'easy-medium', source:'Bhagavad-gītā', reference:'BG 6.47', text:`yoginām api sarveṣāṁ\nmad-gatenāntarātmanā\nśraddhāvān bhajate yo māṁ\nsa me yuktatamo mataḥ`, translation:'Of all yogīs, the one with great faith who worships Me is the most intimately united with Me.' },

  // Medium
  { id:'bg-2.47', meter:'anushtubh', difficulty:'medium', source:'Bhagavad-gītā', reference:'BG 2.47', text:`karmaṇy evādhikāras te\nmā phaleṣu kadācana\nmā karma-phala-hetur bhūr\nmā te saṅgo 'stv akarmaṇi`, translation:'You have a right to perform your duty, but not to the fruits of action.' },
  { id:'bg-2.20', meter:'anushtubh', difficulty:'medium', source:'Bhagavad-gītā', reference:'BG 2.20', text:`na jāyate mriyate vā kadācin\nnāyaṁ bhūtvā bhavitā vā na bhūyaḥ\najo nityaḥ śāśvato 'yaṁ purāṇo\nna hanyate hanyamāne śarīre`, translation:'The soul is never born nor dies. It is unborn, eternal, ever-existing, and primeval.' },
  { id:'bg-3.21', meter:'anushtubh', difficulty:'medium', source:'Bhagavad-gītā', reference:'BG 3.21', text:`yad yad ācarati śreṣṭhas\ntat tad evetaro janaḥ\nsa yat pramāṇaṁ kurute\nlokas tad anuvartate`, translation:'Whatever a great man does, common men follow.' },
  { id:'bg-5.29', meter:'anushtubh', difficulty:'medium', source:'Bhagavad-gītā', reference:'BG 5.29', text:`bhoktāraṁ yajña-tapasāṁ\nsarva-loka-maheśvaram\nsuhṛdaṁ sarva-bhūtānāṁ\njñātvā māṁ śāntim ṛcchati`, translation:'Knowing Me as the enjoyer of sacrifice, the supreme lord and friend of all beings, one attains peace.' },
  { id:'bg-10.10', meter:'anushtubh', difficulty:'medium', source:'Bhagavad-gītā', reference:'BG 10.10', text:`teṣāṁ satata-yuktānāṁ\nbhajatāṁ prīti-pūrvakam\ndadāmi buddhi-yogaṁ taṁ\nyena mām upayānti te`, translation:'To those who worship Me with love, I give the understanding by which they can come to Me.' },
  { id:'bg-4.34', meter:'anushtubh', difficulty:'medium', source:'Bhagavad-gītā', reference:'BG 4.34', text:`tad viddhi praṇipātena\nparipraśnena sevayā\nupadekṣyanti te jñānaṁ\njñāninas tattva-darśinaḥ`, translation:'Learn the truth by approaching a spiritual master. Inquire submissively and render service.' },

  // Medium-Hard
  { id:'bg-4.7', meter:'anushtubh', difficulty:'medium-hard', source:'Bhagavad-gītā', reference:'BG 4.7', text:`yadā yadā hi dharmasya\nglānir bhavati bhārata\nabhyutthānam adharmasya\ntadātmānaṁ sṛjāmy aham`, translation:'Whenever there is a decline of dharma, I manifest Myself.' },
  { id:'bg-18.65', meter:'anushtubh', difficulty:'medium-hard', source:'Bhagavad-gītā', reference:'BG 18.65', text:`man-manā bhava mad-bhakto\nmad-yājī māṁ namaskuru\nmām evaiṣyasi satyaṁ te\npratijāne priyo 'si me`, translation:'Think of Me, be My devotee, worship Me — you will come to Me. I truly promise this.' },
  { id:'bg-2.62', meter:'anushtubh', difficulty:'medium-hard', source:'Bhagavad-gītā', reference:'BG 2.62', text:`dhyāyato viṣayān puṁsaḥ\nsaṅgas teṣūpajāyate\nsaṅgāt sañjāyate kāmaḥ\nkāmāt krodho 'bhijāyate`, translation:'Contemplating sense objects breeds attachment; from attachment lust develops; from lust anger arises.' },
  { id:'bg-9.2', meter:'anushtubh', difficulty:'medium-hard', source:'Bhagavad-gītā', reference:'BG 9.2', text:`rāja-vidyā rāja-guhyaṁ\npavitram idam uttamam\npratyakṣāvagamaṁ dharmyaṁ\nsu-sukhaṁ kartum avyayam`, translation:'This knowledge is the king of education, the most secret, purest, directly perceivable, and everlasting.' },

  // Hard
  { id:'bg-13.13', meter:'anushtubh', difficulty:'hard', source:'Bhagavad-gītā', reference:'BG 13.13', text:`jñeyaṁ yat tat pravakṣyāmi\nyaj jñātvāmṛtam aśnute\nanādi mat-paraṁ brahma\nna sat tan nāsad ucyate`, translation:'I shall explain the knowable, knowing which you will taste the eternal.' },
  { id:'bg-18.54', meter:'anushtubh', difficulty:'hard', source:'Bhagavad-gītā', reference:'BG 18.54', text:`brahma-bhūtaḥ prasannātmā\nna śocati na kāṅkṣati\nsamaḥ sarveṣu bhūteṣu\nmad-bhaktiṁ labhate parām`, translation:'One in the transcendental position realizes Brahman and achieves pure devotion unto Me.' },
  { id:'bg-8.5', meter:'anushtubh', difficulty:'hard', source:'Bhagavad-gītā', reference:'BG 8.5', text:`anta-kāle ca mām eva\nsmaran muktvā kalevaram\nyaḥ prayāti sa mad-bhāvaṁ\nyāti nāsty atra saṁśayaḥ`, translation:'Whoever remembers Me at death, leaving the body, attains My nature. No doubt.' },
  { id:'bg-11.55', meter:'anushtubh', difficulty:'hard', source:'Bhagavad-gītā', reference:'BG 11.55', text:`mat-karma-kṛn mat-paramo\nmad-bhaktaḥ saṅga-varjitaḥ\nnirvairaḥ sarva-bhūteṣu\nyaḥ sa mām eti pāṇḍava`, translation:'One who works for Me, free from attachment and enmity — he comes to Me.' },

  // ══════ ŚRĪMAD-BHĀGAVATAM ══════

  { id:'sb-1.2.6', meter:'anushtubh', difficulty:'medium', source:'Śrīmad-Bhāgavatam', reference:'ŚB 1.2.6', text:`sa vai puṁsāṁ paro dharmo\nyato bhaktir adhokṣaje\nahaituky apratihatā\nyayātmā suprasīdati`, translation:'The supreme dharma is causeless and uninterrupted devotion to the Lord.' },
  { id:'sb-1.2.11', meter:'anushtubh', difficulty:'medium-hard', source:'Śrīmad-Bhāgavatam', reference:'ŚB 1.2.11', text:`vadanti tat tattva-vidas\ntattvaṁ yaj jñānam advayam\nbrahmeti paramātmeti\nbhagavān iti śabdyate`, translation:'The Absolute Truth is known as Brahman, Paramātmā, and Bhagavān.' },
  { id:'sb-1.2.17', meter:'anushtubh', difficulty:'medium', source:'Śrīmad-Bhāgavatam', reference:'ŚB 1.2.17', text:`śṛṇvatāṁ sva-kathāḥ kṛṣṇaḥ\npuṇya-śravaṇa-kīrtanaḥ\nhṛdy antaḥ stho hy abhadrāṇi\nvidhunoti suhṛt satām`, translation:'Kṛṣṇa, seated within the heart, destroys inauspiciousness for those who hear about Him.' },
  { id:'sb-1.2.18', meter:'anushtubh', difficulty:'medium-hard', source:'Śrīmad-Bhāgavatam', reference:'ŚB 1.2.18', text:`naṣṭa-prāyeṣv abhadreṣu\nnityaṁ bhāgavata-sevayā\nbhagavaty uttama-śloke\nbhaktir bhavati naiṣṭhikī`, translation:'By regular Bhāgavatam study, all troubles are destroyed, and loving devotion is established.' },
  { id:'sb-1.3.28', meter:'anushtubh', difficulty:'easy-medium', source:'Śrīmad-Bhāgavatam', reference:'ŚB 1.3.28', text:`ete cāṁśa-kalāḥ puṁsaḥ\nkṛṣṇas tu bhagavān svayam\nindrāri-vyākulaṁ lokaṁ\nmṛḍayanti yuge yuge`, translation:'All incarnations are portions or portions of portions, but Kṛṣṇa is the Supreme Personality of Godhead Himself.' },
  { id:'sb-7.5.23', meter:'trishtubh', difficulty:'easy', source:'Śrīmad-Bhāgavatam', reference:'ŚB 7.5.23', text:`śravaṇaṁ kīrtanaṁ viṣṇoḥ\nsmaraṇaṁ pāda-sevanam\narcanaṁ vandanaṁ dāsyaṁ\nsakhyam ātma-nivedanam`, translation:'Hearing, chanting, remembering Viṣṇu, serving His feet, worshiping, praying, serving, friendship, and self-surrender.' },
  { id:'sb-7.5.32', meter:'trishtubh', difficulty:'medium-hard', source:'Śrīmad-Bhāgavatam', reference:'ŚB 7.5.32', text:`naiṣāṁ matis tāvad urukramāṅghriṁ\nspṛśaty anarthāpagamo yad-arthaḥ\nmahīyasāṁ pāda-rajo-'bhiṣekaṁ\nniṣkiñcanānāṁ na vṛṇīta yāvat`, translation:'One cannot understand the Lord until one receives the dust of the feet of great devotees.' },
  { id:'sb-3.25.25', meter:'trishtubh', difficulty:'medium', source:'Śrīmad-Bhāgavatam', reference:'ŚB 3.25.25', text:`satāṁ prasaṅgān mama vīrya-saṁvido\nbhavanti hṛt-karṇa-rasāyanāḥ kathāḥ\ntaj-joṣaṇād āśv apavarga-vartmani\nśraddhā ratir bhaktir anukramiṣyati`, translation:'In devotee association, discussions of My glories become pleasing; faith, attachment and devotion develop.' },
  { id:'sb-10.14.8', meter:'trishtubh', difficulty:'hard', source:'Śrīmad-Bhāgavatam', reference:'ŚB 10.14.8', text:`tat te 'nukampāṁ su-samīkṣamāṇo\nbhuñjāna evātma-kṛtaṁ vipākam\nhṛd-vāg-vapurbhir vidadhan namas te\njīveta yo mukti-pade sa dāya-bhāk`, translation:'One who awaits Your compassion while tolerating past karma is eligible for liberation.' },
  { id:'sb-10.51.53', meter:'jagati', difficulty:'easy-medium', source:'Śrīmad-Bhāgavatam', reference:'ŚB 10.51.53', text:`bhavāpavargo bhramato yadā bhavej\njanasya tarhy acyuta sat-samāgamaḥ\nsat-saṅgamo yarhi tadaiva sad-gatau\nparāvareśe tvayi jāyate matiḥ`, translation:'When liberation is due, a wandering soul gets devotee association, then devotion to You arises.' },
  { id:'sb-11.2.37', meter:'jagati', difficulty:'medium', source:'Śrīmad-Bhāgavatam', reference:'ŚB 11.2.37', text:`bhayaṁ dvitīyābhiniveśataḥ syād\nīśād apetasya viparyayo 'smṛtiḥ\ntan-māyayāto budha ābhajet taṁ\nbhaktyaikayeśaṁ guru-devatātmā`, translation:'Fear arises from turning away from the Lord. A wise person should worship Him with exclusive devotion.' },
  { id:'sb-11.5.32', meter:'jagati', difficulty:'medium-hard', source:'Śrīmad-Bhāgavatam', reference:'ŚB 11.5.32', text:`kṛṣṇa-varṇaṁ tviṣākṛṣṇaṁ\nsāṅgopāṅgāstra-pārṣadam\nyajñaiḥ saṅkīrtana-prāyair\nyajanti hi su-medhasaḥ`, translation:'Those with good intelligence worship the Lord who chants Kṛṣṇa\'s name through congregational chanting.' },
  { id:'sb-10.33.39', meter:'jagati', difficulty:'hard', source:'Śrīmad-Bhāgavatam', reference:'ŚB 10.33.39', text:`vikrīḍitaṁ vraja-vadhūbhir idaṁ ca viṣṇoḥ\nśraddhānvito 'nuśṛṇuyād atha varṇayed yaḥ\nbhaktiṁ parāṁ bhagavati pratilabhya kāmaṁ\nhṛd-rogam āśv apahinoty acireṇa dhīraḥ`, translation:'One who faithfully hears about Kṛṣṇa\'s pastimes with the gopīs attains supreme devotion and removes lust.' },
  { id:'sb-6.3.22', meter:'anushtubh', difficulty:'easy-medium', source:'Śrīmad-Bhāgavatam', reference:'ŚB 6.3.22', text:`etāvān eva loke 'smin\npuṁsāṁ dharmaḥ paraḥ smṛtaḥ\nbhakti-yogo bhagavati\ntan-nāma-grahaṇādibhiḥ`, translation:'The supreme dharma is devotional service beginning with chanting His holy names.' },
  { id:'sb-2.4.18', meter:'anushtubh', difficulty:'hard', source:'Śrīmad-Bhāgavatam', reference:'ŚB 2.4.18', text:`kirāta-hūṇāndhra-pulinda-pulkaśā\nābhīra-śumbhā yavanāḥ khasādayaḥ\nye 'nye ca pāpā yad-apāśrayāśrayāḥ\nśudhyanti tasmai prabhaviṣṇave namaḥ`, translation:'Even the most sinful can be purified by taking shelter of the Lord\'s devotees.' },
  { id:'sb-2.3.17', meter:'trishtubh', difficulty:'easy-medium', source:'Śrīmad-Bhāgavatam', reference:'ŚB 2.3.17', text:`āyur harati vai puṁsām\nudyann astaṁ ca yann asau\ntasyarte yat-kṣaṇo nīta\nuttama-śloka-vārtayā`, translation:'The sun diminishes everyone\'s life — except for those who use time discussing the Supreme Lord.' },
  { id:'sb-10.14.3', meter:'longer', difficulty:'hard', source:'Śrīmad-Bhāgavatam', reference:'ŚB 10.14.3', text:`jñāne prayāsam udapāsya namanta eva\njīvanti san-mukharitāṁ bhavadīya-vārtām\nsthāne sthitāḥ śruti-gatāṁ tanu-vāṅ-manobhir\nye prāyaśo 'jita jito 'py asi tais tri-lokyām`, translation:'Those who hear Your glories from devotees, remaining in their position, can conquer the unconquerable.' },

  // ══════ BRAHMA-SAṀHITĀ (vasanta-tilakā) ══════

  { id:'bs-5.1', meter:'vasanta_tilaka', difficulty:'easy-medium', source:'Brahma-saṁhitā', reference:'BS 5.1', text:`īśvaraḥ paramaḥ kṛṣṇaḥ\nsac-cid-ānanda-vigrahaḥ\nanādir ādir govindaḥ\nsarva-kāraṇa-kāraṇam`, translation:'Kṛṣṇa is the Supreme Godhead with an eternal blissful body. He is the cause of all causes.' },
  { id:'bs-5.29', meter:'vasanta_tilaka', difficulty:'medium', source:'Brahma-saṁhitā', reference:'BS 5.29', text:`cintāmaṇi-prakara-sadmasu kalpa-vṛkṣa-\nlakṣāvṛteṣu surabhīr abhipālayantam\nlakṣmī-sahasra-śata-sambhrama-sevyamānaṁ\ngovindam ādi-puruṣaṁ tam ahaṁ bhajāmi`, translation:'I worship Govinda who tends cows in abodes of cintāmaṇi, served by hundreds of thousands of Lakṣmīs.' },
  { id:'bs-5.30', meter:'vasanta_tilaka', difficulty:'medium', source:'Brahma-saṁhitā', reference:'BS 5.30', text:`veṇuṁ kvaṇantam aravinda-dalāyatākṣam-\nbarhāvataṁsam asitāmbuda-sundarāṅgam\nkandarpa-koṭi-kamanīya-viśeṣa-śobhaṁ\ngovindam ādi-puruṣaṁ tam ahaṁ bhajāmi`, translation:'I worship Govinda who plays the flute, with lotus eyes, peacock feather, beauty surpassing millions of Cupids.' },
  { id:'bs-5.31', meter:'vasanta_tilaka', difficulty:'medium-hard', source:'Brahma-saṁhitā', reference:'BS 5.31', text:`ālola-candraka-lasad-vanamālya-vaṁśī-\nratnāṅgadaṁ praṇaya-keli-kalā-vilāsam\nśyāmaṁ tri-bhaṅga-lalitaṁ niyata-prakāśaṁ\ngovindam ādi-puruṣaṁ tam ahaṁ bhajāmi`, translation:'I worship Govinda, adorned with garland, flute, jeweled armlets, standing in His three-fold bending form.' },
  { id:'bs-5.32', meter:'vasanta_tilaka', difficulty:'medium-hard', source:'Brahma-saṁhitā', reference:'BS 5.32', text:`aṅgāni yasya sakalendriya-vṛtti-manti\npaśyanti pānti kalayanti ciraṁ jaganti\nānanda-cin-maya-sad-ujjvala-vigrahasya\ngovindam ādi-puruṣaṁ tam ahaṁ bhajāmi`, translation:'I worship Govinda whose limbs can perform all functions, who eternally maintains all universes.' },
  { id:'bs-5.33', meter:'vasanta_tilaka', difficulty:'hard', source:'Brahma-saṁhitā', reference:'BS 5.33', text:`advaitam acyutam anādim ananta-rūpam\nādyaṁ purāṇa-puruṣaṁ nava-yauvanaṁ ca\nvedeṣu durlabham adurlabham ātma-bhaktau\ngovindam ādi-puruṣaṁ tam ahaṁ bhajāmi`, translation:'I worship Govinda — undivided, infallible, beginningless, with unlimited forms, the oldest yet always a fresh youth.' },
  { id:'bs-5.35', meter:'vasanta_tilaka', difficulty:'hard', source:'Brahma-saṁhitā', reference:'BS 5.35', text:`eko 'py asau racayituṁ jagad-aṇḍa-koṭiṁ\nyac-chaktir asti jagad-aṇḍa-cayā yad-antaḥ\naṇḍāntara-stha-paramāṇu-cayāntara-sthaṁ\ngovindam ādi-puruṣaṁ tam ahaṁ bhajāmi`, translation:'I worship Govinda who enters each universe and every atom by one plenary portion.' },
  { id:'bs-5.38', meter:'vasanta_tilaka', difficulty:'medium', source:'Brahma-saṁhitā', reference:'BS 5.38', text:`premāñjana-cchurita-bhakti-vilocanena\nsantaḥ sadaiva hṛdayeṣu vilokayanti\nyaṁ śyāmasundaram acintya-guṇa-svarūpaṁ\ngovindam ādi-puruṣaṁ tam ahaṁ bhajāmi`, translation:'I worship Govinda whom devotees always see in their hearts with eyes anointed with the ointment of love.' },
  { id:'bs-5.40', meter:'vasanta_tilaka', difficulty:'easy', source:'Brahma-saṁhitā', reference:'BS 5.40', text:`yasya prabhā prabhavato jagad-aṇḍa-koṭi-\nkoṭiṣv aśeṣa-vasudhādi-vibhūti-bhinnam\ntad brahma niṣkalam anantam aśeṣa-bhūtaṁ\ngovindam ādi-puruṣaṁ tam ahaṁ bhajāmi`, translation:'I worship Govinda whose effulgence is the source of the Brahman containing millions of universes.' },

  // ══════ CAITANYA-CARITĀMṚTA & ŚIKṢĀṢṬAKA ══════

  { id:'cc-adi-1.4', meter:'longer', difficulty:'medium-hard', source:'Caitanya-caritāmṛta', reference:'CC Ādi 1.4', text:`anarpita-carīṁ cirāt karuṇayāvatīrṇaḥ kalau\nsamarpayitum unnatojjvala-rasāṁ sva-bhakti-śriyam\nhariḥ puraṭa-sundara-dyuti-kadamba-sandīpitaḥ\nsadā hṛdaya-kandare sphuratu vaḥ śacī-nandanaḥ`, translation:'May the Lord who descended in Kali-yuga to bestow the most elevated devotion always manifest in your hearts.' },
  { id:'sa-1', meter:'longer', difficulty:'hard', source:'Śikṣāṣṭaka', reference:'Śikṣāṣṭaka 1', text:`ceto-darpaṇa-mārjanaṁ bhava-mahā-dāvāgni-nirvāpaṇaṁ\nśreyaḥ-kairava-candrikā-vitaraṇaṁ vidyā-vadhū-jīvanam\nānandāmbudhi-vardhanaṁ prati-padaṁ pūrṇāmṛtāsvādanaṁ\nsarvātma-snapanaṁ paraṁ vijayate śrī-kṛṣṇa-saṅkīrtanam`, translation:'All victory for the chanting of Śrī Kṛṣṇa which cleanses the mirror of the heart.' },
  { id:'sa-2', meter:'longer', difficulty:'medium', source:'Śikṣāṣṭaka', reference:'Śikṣāṣṭaka 2', text:`nāmnām akāri bahudhā nija-sarva-śaktis\ntatrārpitā niyamitaḥ smaraṇe na kālaḥ\netādṛśī tava kṛpā bhagavan mamāpi\ndurdaivam īdṛśam ihājani nānurāgaḥ`, translation:'O Lord, Your holy name bestows all auspiciousness. Yet my misfortune is that I have no attraction.' },
  { id:'sa-3', meter:'anushtubh', difficulty:'medium-hard', source:'Śikṣāṣṭaka', reference:'Śikṣāṣṭaka 3', text:`tṛṇād api sunīcena\ntaror api sahiṣṇunā\namāninā mānadena\nkīrtanīyaḥ sadā hariḥ`, translation:'One should be humbler than a blade of grass, more tolerant than a tree. In such a state one can chant constantly.' },
  { id:'sa-8', meter:'longer', difficulty:'medium', source:'Śikṣāṣṭaka', reference:'Śikṣāṣṭaka 8', text:`āśliṣya vā pāda-ratāṁ pinaṣṭu mām\nadarśanān marma-hatāṁ karotu vā\nyathā tathā vā vidadhātu lampaṭo\nmat-prāṇa-nāthas tu sa eva nāparaḥ`, translation:'Let Kṛṣṇa embrace me or trample me — He is the Lord of my life.' },

  // ══════ ĪŚOPANIṢAD ══════

  { id:'iso-1', meter:'anushtubh', difficulty:'medium', source:'Īśopaniṣad', reference:'Īśo 1', text:`īśāvāsyam idaṁ sarvaṁ\nyat kiñca jagatyāṁ jagat\ntena tyaktena bhuñjīthā\nmā gṛdhaḥ kasya svid dhanam`, translation:'Everything belongs to the Lord. One should accept only what one needs and not covet others\' property.' },

  // ══════ MANTRAS & CHANTS ══════

  { id:'man-e1', meter:'mantra', difficulty:'easy', source:'Mahā-mantra', reference:'Hare Kṛṣṇa Mahā-mantra', text:`hare kṛṣṇa hare kṛṣṇa\nkṛṣṇa kṛṣṇa hare hare\nhare rāma hare rāma\nrāma rāma hare hare`, translation:'The great chant for deliverance.' },
  { id:'man-e2', meter:'mantra', difficulty:'easy', source:'Praṇāma Mantra', reference:'Oṁ namo bhagavate vāsudevāya', text:`oṁ namo bhagavate vāsudevāya`, translation:'I offer my obeisances to the Supreme Lord Vāsudeva.' },
  { id:'man-e3', meter:'mantra', difficulty:'easy', source:'Pañca-tattva Mahā-mantra', reference:'Pañca-tattva Mantra', text:`jaya śrī-kṛṣṇa-caitanya\nprabhu nityānanda\nśrī-advaita gadādhara\nśrīvāsādi-gaura-bhakta-vṛnda`, translation:'Glory to Lord Caitanya, Prabhu Nityānanda, Śrī Advaita, Gadādhara, and all devotees of Lord Gaura.' },
  { id:'man-e4', meter:'mantra', difficulty:'easy', source:'Praṇāma', reference:'Haribol', text:`haribol haribol haribol`, translation:'Chant the name of Hari!' },
  { id:'man-e5', meter:'mantra', difficulty:'easy', source:'Nṛsiṁha Praṇāma', reference:'Nṛsiṁha Praṇāma', text:`namas te narasiṁhāya\nprahlādāhlāda-dāyine\nhiraṇyakaśipor vakṣaḥ-\nśilā-ṭaṅka-nakhālaye`, translation:'Obeisances to Lord Narasiṁha, who gives joy to Prahlāda.' },
  { id:'man-em1', meter:'mantra', difficulty:'easy-medium', source:'Prabhupāda Praṇāma', reference:'Guru Praṇāma', text:`nama oṁ viṣṇu-pādāya kṛṣṇa-preṣṭhāya bhū-tale\nśrīmate bhaktivedānta-svāmin iti nāmine\nnamas te sārasvate deve gaura-vāṇī-pracāriṇe\nnirviśeṣa-śūnyavādi-pāścātya-deśa-tāriṇe`, translation:'Obeisances to Śrīla Prabhupāda, delivering the Western countries.' },
  { id:'man-em2', meter:'mantra', difficulty:'easy-medium', source:'Tulasī Āratī', reference:'Tulasī Praṇāma', text:`vṛndāyai tulasī-devyai\npriyāyai keśavasya ca\nkṛṣṇa-bhakti-prade devī\nsatyavatyai namo namaḥ`, translation:'Obeisances to Tulasī-devī, who bestows devotion to Kṛṣṇa.' },
  { id:'man-em3', meter:'mantra', difficulty:'easy-medium', source:'Bhaktivinoda Ṭhākura', reference:'Jīv Jāgo', text:`jīv jāgo jīv jāgo gauracānda bole\nkota nidrā jāo māyā-piśācīra kole`, translation:'Wake up sleeping souls! How long will you sleep in the lap of Māyā?' },
  { id:'man-m1', meter:'mantra', difficulty:'medium', source:'Śrī Guru Praṇāma', reference:'Guru Vandanā', text:`oṁ ajñāna-timirāndhasya\njñānāñjana-śalākayā\ncakṣur unmīlitaṁ yena\ntasmai śrī-gurave namaḥ`, translation:'My spiritual master opened my eyes with the torch of knowledge.' },
  { id:'man-m2', meter:'mantra', difficulty:'medium', source:'Gāyatrī', reference:'Brahma-gāyatrī', text:`oṁ bhūr bhuvaḥ svaḥ\ntat savitur vareṇyaṁ\nbhargo devasya dhīmahi\ndhiyo yo naḥ pracodayāt`, translation:'Let us meditate upon the glorious effulgence of the divine creator.' },
  { id:'man-m3', meter:'mantra', difficulty:'medium', source:'Nṛsiṁha Prayers', reference:'Nṛsiṁha Kavacha', text:`ito nṛsiṁhaḥ parato nṛsiṁho\nyato yato yāmi tato nṛsiṁhaḥ\nbahir nṛsiṁho hṛdaye nṛsiṁho\nnṛsiṁham ādiṁ śaraṇaṁ prapadye`, translation:'Lord Nṛsiṁha is here and there, wherever I go. I surrender to that primeval Lord.' },
  { id:'man-mh1', meter:'mantra', difficulty:'medium-hard', source:'Dāmodarāṣṭaka', reference:'Dāmodarāṣṭaka 1', text:`namāmīśvaraṁ sac-cid-ānanda-rūpaṁ\nlasat-kuṇḍalaṁ gokule bhrājamanam\nyaśodā-bhiyolūkhalād dhāvamānaṁ\nparāmṛṣṭam atyantato drutya gopyā`, translation:'I bow to the Supreme Lord in bliss form, fleeing from the mortar in Gokula, caught by Yaśodā.' },
  { id:'man-mh2', meter:'mantra', difficulty:'medium-hard', source:'Gurv-aṣṭaka', reference:'Gurv-aṣṭaka 1', text:`saṁsāra-dāvānala-līḍha-loka-\ntrāṇāya kāruṇya-ghanāghanatvam\nprāptasya kalyāṇa-guṇārṇavasya\nvande guroḥ śrī-caraṇāravindam`, translation:'The guru, an ocean of auspicious qualities, appeared out of compassion to deliver the burning world.' },

  // ══════ ISKCON BHAJANS ══════

  // Bhaktivinoda Ṭhākura
  { id:'bj-1', meter:'mantra', difficulty:'easy', source:'Bhaktivinoda Ṭhākura', reference:'Gurudeva! (1)', text:`gurudeva!\nkṛpā-bindu diyā koro' ei dāse\ntṛṇāpekhā ati hīna\nsakala sahane bala diyā koro'\nnija-māne spṛhā-hīna`, translation:'O Gurudeva! Give just a drop of mercy. Make me humbler than a blade of grass and give me strength to bear all trials.' },
  { id:'bj-2', meter:'mantra', difficulty:'easy', source:'Bhaktivinoda Ṭhākura', reference:'Jaya Rādhā-Mādhava', text:`jaya rādhā-mādhava jaya kuñja-bihārī\njaya gopī-jana-vallabha jaya giri-vara-dhārī\nyaśodā-nandana braja-jana-raṇjana\nyamunā-tīra-vana-cārī`, translation:'All glories to Rādhā-Mādhava, the enjoyer of the groves, the lifter of Govardhana, the son of Yaśodā who wanders along the Yamunā.' },
  { id:'bj-3', meter:'mantra', difficulty:'easy-medium', source:'Bhaktivinoda Ṭhākura', reference:'Śrī Nāma (Harer nāma)', text:`harer nāma harer nāma\nharer nāmaiva kevalam\nkalau nāsty eva nāsty eva\nnāsty eva gatir anyathā`, translation:'In this age of Kali there is no other means of spiritual progress than the chanting of the holy name.' },
  { id:'bj-4', meter:'mantra', difficulty:'medium', source:'Bhaktivinoda Ṭhākura', reference:'Kabe Habe Bolo (1)', text:`kabe ha'be bolo se-dina āmār\naparādha ghuci' śuddha nāme ruci\nkṛpā-bale ha'be hṛdoye sañcār`, translation:'When, oh when will that day be mine? When will my offenses end and a taste for the pure holy name arise in my heart?' },
  { id:'bj-5', meter:'mantra', difficulty:'easy', source:'Bhaktivinoda Ṭhākura', reference:'Bhaja Hu Re Mana (1)', text:`bhaja hu re mana śrī-nanda-nandana\nabhaya-caraṇāravinda re\ndurlapha mānava-janama sat-saṅge\ntaroho e bhava-sindhu re`, translation:'O mind, worship the son of Nanda whose lotus feet grant fearlessness. This rare human life, in good association, can cross the ocean of birth and death.' },
  { id:'bj-6', meter:'mantra', difficulty:'medium', source:'Bhaktivinoda Ṭhākura', reference:'Jīv Jāgo (full)', text:`jīv jāgo jīv jāgo gauracānda bole\nkota nidrā jāo māyā-piśācīra kole\nbhajibo boliyā ese saṁsāra-bhitore\nbhuliyā rohile tumi avidyāra bhore`, translation:'Lord Gauracānda says: Wake up! How long will you sleep in Māyā\'s lap? You came to this world saying you would worship, but you forgot in the darkness of ignorance.' },
  { id:'bj-7', meter:'mantra', difficulty:'medium-hard', source:'Bhaktivinoda Ṭhākura', reference:'Ātma-nivedana (1)', text:`mānasa deho geho jo kichu mor\narpiluṅ tuwā pade nanda-kiśor\nsampade vipade jīvane-maraṇe\ndāy mama gelā tuwā o-pada varaṇe`, translation:'Mind, body, home — whatever I have I surrender at Your feet, O Nanda-kiśora. In good fortune or misfortune, life or death, I have accepted Your lotus feet.' },

  // Narottama dāsa Ṭhākura
  { id:'bj-8', meter:'mantra', difficulty:'easy-medium', source:'Narottama dāsa Ṭhākura', reference:'Hari Hari Biphale (1)', text:`hari hari biphale janama goṅāinu\nmanuṣya-janama pāiyā rādhā-kṛṣṇa nā bhajiyā\njāniyā śuniyā biṣa khāinu`, translation:'O Lord Hari, I have wasted my life! Obtaining a human birth, I failed to worship Rādhā-Kṛṣṇa and have knowingly drunk poison.' },
  { id:'bj-9', meter:'mantra', difficulty:'medium', source:'Narottama dāsa Ṭhākura', reference:'Gaurāṅga Bolite Habe (1)', text:`gaurāṅga bolite habe pulaka śarīra\nhari hari bolite nayane ba'be nīra\nāra kabe nitāicā̃da koruṇā koribe\nsaṁsāra-bāsanā mora kabe tuccha habe`, translation:'When will my body thrill at the name of Gaurāṅga? When will tears flow from my eyes at the name of Hari?' },
  { id:'bj-10', meter:'mantra', difficulty:'easy', source:'Narottama dāsa Ṭhākura', reference:'Śrī Rūpa Mañjarī Pada (1)', text:`śrī-rūpa-mañjarī-pada sei mora sampada\nsei mora bhajana-pūjana\nsei mora prāṇa-dhana sei mora ābharaṇa\nsei mora jīvanera jīvana`, translation:'The lotus feet of Śrī Rūpa Mañjarī are my treasure, my worship, my wealth, my ornament, and the life of my life.' },
  { id:'bj-11', meter:'mantra', difficulty:'easy-medium', source:'Narottama dāsa Ṭhākura', reference:'Sapārṣada (Hari Haraye Namaḥ)', text:`hari haraye namaḥ kṛṣṇa yādavāya namaḥ\nyādavāya mādhavāya keśavāya namaḥ\ngopāla govinda rāma śrī-madhusūdana\ngiridharī gopīnātha madana-mohana`, translation:'I offer my obeisances to Hari, Kṛṣṇa, Yādava, Mādhava, Keśava — Gopāla, Govinda, Rāma, Madhusūdana, Giridharī, Gopīnātha, Madana-mohana.' },

  // Śrīla Viśvanātha Cakravartī Ṭhākura
  { id:'bj-12', meter:'mantra', difficulty:'medium-hard', source:'Viśvanātha Cakravartī Ṭhākura', reference:'Gurv-aṣṭaka 2', text:`mahāprabhoḥ kīrtana-nṛtya-gīta-\nvāditra-mādyan-manaso rasena\nromāñca-kampāśru-taraṅga-bhājo\nvande guroḥ śrī-caraṇāravindam`, translation:'The guru is always chanting, dancing, and playing instruments, overwhelmed by ecstasy. I worship his lotus feet.' },
  { id:'bj-13', meter:'mantra', difficulty:'medium-hard', source:'Viśvanātha Cakravartī Ṭhākura', reference:'Gurv-aṣṭaka 7', text:`sākṣād-dharitvena samasta-śāstrair\nuktas tathā bhāvyata eva sadbhiḥ\nkintu prabhor yaḥ priya eva tasya\nvande guroḥ śrī-caraṇāravindam`, translation:'The guru is worshipped as the direct manifestation of the Lord, yet he is most dear to the Lord. I worship his lotus feet.' },

  // Popular kīrtana refrains
  { id:'bj-14', meter:'mantra', difficulty:'easy', source:'Kīrtana', reference:'Nitāi-Gaura Nām', text:`nitāi-gaura hari bol\nhari bol hari bol hari bol\nnitāi-gaura hari bol\nhari bol hari bol hari bol`, translation:'Chant the names of Nitāi and Gaura! Chant the name of Hari!' },
  { id:'bj-15', meter:'mantra', difficulty:'easy', source:'Kīrtana', reference:'Govinda Jaya Jaya', text:`govinda jaya jaya gopāla jaya jaya\nrādhā-ramaṇa hari govinda jaya jaya`, translation:'All glories to Govinda! All glories to Gopāla! All glories to Hari, the lover of Rādhā!' },
  { id:'bj-16', meter:'mantra', difficulty:'easy', source:'Kīrtana', reference:'Rādhe Rādhe Govinda', text:`rādhe rādhe rādhe rādhe\ngovinda govinda\nrādhe rādhe rādhe rādhe\ngovinda govinda`, translation:'Rādhe Rādhe! Govinda Govinda! A beloved kīrtana refrain.' },
  { id:'bj-17', meter:'mantra', difficulty:'easy-medium', source:'Kīrtana', reference:'Parama Koruṇa', text:`parama koruṇa pahū dui jana\nnitāi gauracandra\nsaba avatāra-sāra śiromaṇi\nkevala ānanda-kanda`, translation:'The two most merciful Lords are Nitāi and Gauracandra. Of all incarnations, They are the essence, the crest-jewels, the root of pure bliss.' },

  // Āratī songs
  { id:'bj-18', meter:'mantra', difficulty:'medium', source:'Bhaktivinoda Ṭhākura', reference:'Gaura Āratī (1)', text:`kiba jaya jaya gorācā̃der āratiko śobhā\njāhnavī-taṭa-vane jaga-mana-lobhā\ngaurāṅger āratik śobhā jaga-jana-mana-lobhā`, translation:'All glories to the beautiful āratī ceremony of Lord Caitanya on the bank of the Jāhnavī. It captivates the minds of all.' },
  { id:'bj-19', meter:'mantra', difficulty:'medium', source:'Śrīla Prabhupāda', reference:'Jaya Rādhā-Mādhava (Āratī)', text:`jaya rādhā-mādhava kuñja-bihārī\ngopī-jana-vallabha giri-vara-dhārī\nyaśodā-nandana braja-jana-raṇjana\nyamunā-tīra-vana-cārī\nrāsa-raseshvara dhira samira mandira bansibata\nrati-rasa-vasheshvara`, translation:'All glories to Rādhā-Mādhava, the enjoyer of Vṛndāvana, lifter of Govardhana, son of Yaśodā, Lord of the rāsa dance.' },

  // Śrīla Rūpa Gosvāmī
  { id:'bj-20', meter:'mantra', difficulty:'medium-hard', source:'Rūpa Gosvāmī', reference:'Namaḥ Mahā-vadānyāya', text:`namo mahā-vadānyāya\nkṛṣṇa-prema-pradāya te\nkṛṣṇāya kṛṣṇa-caitanya-\nnāmne gaura-tviṣe namaḥ`, translation:'I bow to the most munificent incarnation, who freely gives love of Kṛṣṇa — to Lord Kṛṣṇa Himself, appearing with a golden complexion as Kṛṣṇa Caitanya.' },
]

// Helper functions
export function getSlokasByMeter(meter: Meter): SlokaEntry[] { return slokaLibrary.filter(s => s.meter === meter) }
export function getSlokasByDifficulty(difficulty: Difficulty): SlokaEntry[] { return slokaLibrary.filter(s => s.difficulty === difficulty) }
export function getSlokasByMeterAndDifficulty(meter: Meter, difficulty: Difficulty): SlokaEntry[] { return slokaLibrary.filter(s => s.meter === meter && s.difficulty === difficulty) }

export const difficultyLabels: Record<Difficulty, string> = { 'easy':'Easy', 'easy-medium':'Easy-Medium', 'medium':'Medium', 'medium-hard':'Medium-Hard', 'hard':'Hard' }
export const difficultyColors: Record<Difficulty, string> = { 'easy':'bg-green-100 text-green-700 border-green-300', 'easy-medium':'bg-lime-100 text-lime-700 border-lime-300', 'medium':'bg-yellow-100 text-yellow-700 border-yellow-300', 'medium-hard':'bg-orange-100 text-orange-700 border-orange-300', 'hard':'bg-red-100 text-red-700 border-red-300' }
